Makefile, README.md, storage/main_test.go, storage/test/test_util.go, updater/main_test.go, worker/main_test.go
At local machine environment, `RunMainTest` start etcd server for each test sections.
This process makes the test unstable.
=> At local machine environment, start etcd server manually

ignitions/common/files/opt/sbin/setup-chronyd-conf, ignitions/common/systemd/chronyd.service
If sched_priority is specified in chrony.conf, the following log is output.
```
chrony[7]: 2018-12-27T23:00:12Z sched_setscheduler() failed
```
=> [ignitions] set realtime scheduler using Systemd's policy instead of chrony.conf

worker/sabakan.go
- This is missing change for #53 to skip uploading private container
images when quay.io auth is not set.
- It had to uploading only public container images by not only `neco
sabakan-upload`, but also `neco-worker`.
=> Bug fix: Do not skip UpdateSabakanContents() when quay.io auth is not set

ignitions/common/files/opt/bin/load-image, ignitions/common/systemd/setup-serf-tags.timer
Since the network becomes unstable with a lot of image loading, increase the number of retries to wait
=> Fix bug: https://circleci.com/gh/cybozu-go/neco/1271

dctest/setup.go, progs/etcdpasswd/sshd.go, progs/etcdpasswd/sudoers.go, worker/etcdpasswd.go
Although etcdpasswd assumes password-less operations, neco did not install
requisite changes for ssh and sudoers.
With this PR, sshd is configured as follows:
* Enable `PubKeyAuthentication`
* Disable `PasswordAuthentication`
* Disregard `.ssh/authorized_keys2`
Users who belong to `sudo` group will not be asked their passwords when using `sudo`.
=> [etcdpasswd] install sudoers and sshd_config

.circleci/config.yml
Because CircleCI resets `master` at the head of working branch (in this case `release`) while
checking out the code, `git merge master` would have no effect.
`git merge origin/master` works as expected.
=> [circleci] merge origin/master instead of master

artifacts.go, artifacts_new.go, etc/ipam.json, ignitions/common/files/etc/hostname, ignitions/common/files/etc/neco/rack, ignitions/common/files/opt/sbin/setup-hw, ignitions/common/files/opt/sbin/setup-local-network, ignitions/common/files/opt/sbin/setup-omsa, ignitions/common/networkd/10-node0.network, progs/etcd/templates.go, progs/sabakan/template.go, progs/serf/templates.go, progs/vault/templates.go, setup/etcd_backup.go
Because sabakan 1.0.0 breaks backward compatibility for ignition
template syntax and ipam.json, they need to be updated.
=> Update ignitions and ipam.json for sabakan 1.0.1

.circleci/config.yml, bin/run-dctest.sh, dctest/machines.go, dctest/upgrade.go, docs/dctest.md, docs/etcd.md, docs/neco-updater.md, docs/neco-worker.md, docs/neco.md, ext/http.go, pkg/neco/cmd/bmc_config_get_ipmipassword.go, pkg/neco/cmd/bmc_config_get_ipmiuser.go, pkg/neco/cmd/config_get.go, pkg/neco/cmd/config_set.go, storage/config.go, storage/keys.go, updater/release_checker.go, updater/server.go, worker/deb.go, worker/deb_test.go, worker/etcdpasswd.go, worker/operator.go
Background:
`neco-updater` periodically checks the latest GitHub release of this repository. But rate limit would be received shortly if it is not authenticated.
Expected:
Set token in etcd, then `neco-updater` and `neco-worker` use it when checks release to prevent the GitHub rate limits.
Also fix an argument bug of the `neco bmc config get ipmipassword`.
=> Support GitHub access token for checking GitHub release

artifacts_new.go, ignitions/common/common.yml, ignitions/common/files/etc/fstab, ignitions/common/files/etc/systemd/system/containerd.service.d/10-wait-mount.conf, ignitions/common/files/etc/systemd/system/docker.service.d/10-wait-mount.conf, ignitions/common/files/etc/systemd/system/docker.service.d/99-run-after-time-sync.conf, ignitions/common/files/etc/systemd/system/docker.socket.d/99-run-after-time-sync.conf, ignitions/common/files/etc/systemd/system/rkt-gc.timer.d/10-wait-mount.conf, ignitions/common/files/opt/sbin/setup-var, ignitions/common/systemd/setup-chrony.service, ignitions/common/systemd/setup-network.service
In order to specify precise dependencies on persistent volumes,
we switch to prepare a logical volume for each service including
containerd, docker, and rkt.
In addition, `/var/lib/kubelet` is also persisted for kubelet.
Ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage
=> [ignition] create LV per service

ignitions/common/systemd/exec-setup-hw.service, ignitions/common/systemd/serf.service, ignitions/common/systemd/setup-hw.service
systemd `Requires=` dependency is too strong when a dependency
service may sometimes fail but then restart successfully.
Ref: https://github.com/systemd/systemd/issues/1312
Instead of `Requires=`, `ExecStartPre=/bin/systemctl is-active -q`
can be used for such cases.
=> [ignition] make robust for temporary service failure

dctest/auto-config, ignitions/common/files/opt/sbin/setup-serf-conf, progs/serf/conf.go, progs/serf/conf_test.go, progs/serf/templates.go
To discover boot server from cluster machines, add `boot-server` tag to serf members.
=> Bootserver tag

bin/run-dctest-release.sh, bin/run-dctest.sh, docs/ignition.md, ignitions/README.md, ignitions/common/common.yml, ignitions/common/files/opt/sbin/bird-wait, ignitions/common/systemd/bird-wait.service, ignitions/common/systemd/chronyd.service, ignitions/common/systemd/cke-images.service, ignitions/common/systemd/coil-image.service, ignitions/common/systemd/neco.target, ignitions/common/systemd/serf.service, ignitions/common/systemd/setup-bmc-user.service, ignitions/common/systemd/setup-hw.service, ignitions/common/systemd/setup-node-exporter.service, ignitions/common/systemd/setup-serf.service, ignitions/common/systemd/squid-image.service
network-online.target is a pre-installed target for systemd.
The purpose of the target is to wait for completion of all
network configurations.
However, the target was not used; instead neco.target was
installed and used for the same purpose.
This commit removes neco.target and simply replace it with
the pre-installed network-online.target.
=> [ignition] replace neco.target with network-online.target

ignitions/common/files/etc/bird/bird.conf
MetalLB runs a BGP speaker to advertise virtual IP addresses
on each Kubernetes node.  Since each node already runs bird as
BGP speaker, MetalLB need to communicate with bird instead of
ToR switches.
In Neco, ASN for MetalLB is `64698` and bound to 127.0.0.1.
BIRD advertises routes from MetalLB as its own routes by
using `next hop self` directive.
In addition, MetalLB routes should not be imported to Node
kernel because packets to the virtual IP addresses are handled
by kube-proxy (IPVS).  To distinguish MetalLB routes, they are
marked with BGP community `(64698,64699)`.
=> [ignitions] add config for MetalLB to bird.conf

ignitions/common/common.yml, ignitions/common/files/opt/sbin/setup-local-network, ignitions/common/networkd/10-node0.netdev, ignitions/common/networkd/10-node0.network
The address of node0 interface need to be advertised by BGP.
It is therefore too early to have node0 interface and address
during DHCP phase.
This commit postpones node0 setup just before running BIRD.
=> [ignitions] delay node0 creation

etc/cke-template.yml
etcd managed by CKE normally requires TLS client certificate
for authentication.  To allow prometheus to pull metrics of
etcd w/o client certs, --listen-metrics-urls=http://0.0.0.0:2381
is given as an extra agument for etcd.
=> [cke] update cluster template to enable metrics for etcd

gcp/compute.go
necogcp uses `gcloud compute disks describe home` command to judge
whether home disk exists or not. It doesn't use --zone option and
expect the default zone to be the zone written in the config file.
=> [necogcp] use correct zone

constants.go, dctest/init.go, dctest/setup.go, progs/cke/install.go, progs/sabakan/install.go, worker/cke.go, worker/sabakan.go
These commands has subcommand `completion` to dump bash completion.
neco-worker installs them onto /etc/bash_completion.d.
=> Install bash completions for ckecli and sabactl

dctest/coil.go, dctest/squid.go, dctest/upgrade.go, etc/squid.yml, ignitions/common/files/etc/systemd/system/docker.service.d/90-proxy.conf, ignitions/common/systemd/k8s-containerd.service
Currently, upgrading container images of node-local DNS cache fails because of two reasons:
1. Squid, the HTTP proxy used by docker / containerd to pull images, depends on the node-local DNS.
2. Docker and containerd themselves depend on node-local DNS to resolve squid hostname.
- Make container runtimes use NodePort to access node-local DNS cache
- Add unbound container to Squid pod and make squid depends on that container.
=> [Bug fix] upgrade unbound

ext/notifier.go, ext/slack.go, ext/slack_test.go, updater/server.go
neco-updater does not send a notification sometimes when
context is canceled due to updating or restarting.
warning: "failed to notify" error="Post https://hooks.slack.com/services/foo/bar context canceled"
Also omit "ts" field from the slack attachment JSON for removing default
time.Time in the notification message.
=> Use different context when updater sends slack notification

dctest/machines.go
`neco bmc setup-hw` in dctest/machines.go failed once.
This does not succeed until `rkt run setup-hw` in setup-hw.service fetches and runs a setup-hw container,
so test it in an eventually loop.
=> [dctest] retry "neco bmc setup-hw".

ignitions/common/systemd/bird-wait.service, ignitions/common/systemd/chrony-wait.service, ignitions/common/systemd/cke-images.service, ignitions/common/systemd/coil-image.service, ignitions/common/systemd/disable-nic-offload.service, ignitions/common/systemd/disable-transparent-hugepage.service, ignitions/common/systemd/exec-setup-hw.service, ignitions/common/systemd/neco-wait-dhcp-online.service, ignitions/common/systemd/sabakan-cryptsetup.service, ignitions/common/systemd/setup-bmc-user.service, ignitions/common/systemd/setup-k8s-containerd.service, ignitions/common/systemd/setup-network.service, ignitions/common/systemd/setup-node-exporter.service, ignitions/common/systemd/setup-serf.service, ignitions/common/systemd/setup-var.service, ignitions/common/systemd/squid-image.service, ignitions/common/systemd/tune-rt-runtime.service, ignitions/common/systemd/wait-k8s-containerd-socket.service
As all service processes with standard output and standard error are connected to the journal by default, we need to wait until we can use journalctl. By this change, the standard outputs and standard errors are also written to serial console and we do not need to wait anymore.
=> [neco] Add settings to service files to write logs to console

Makefile.tools, artifacts.go, etc/coil-deploy.yml
- Update cke version in artifacts.go
- Specify `--ipvs-strict-arp` option for `kube-proxy`
- Replace `beta.kubernetes.io/os` with `kubernetes.io/os`
- Limit process group with `RunAsGroup` in PodSecurityPolicy
- Remove `kustomize` from debian package
=> Update for cke-1.14

storage/worker_watcher.go, updater/server.go
`neco-updater` misunderstood SIGTERM as timeouts.
=> [updater] fix bogus timeout error

gcp/compute.go
"gcloud compute ssh ... date" used different context for retring
access to the instance.
=> [necogcp] Fix a bug

ignitions/common/files/opt/sbin/setup-var, ignitions/common/systemd/setup-var.service
This service monitors LVM2 snapshots and automatically
extends COW blocks when it runs low.
=> [ignition] enable lvm2-monitor.service

gcp/artifacts.go, gcp/config.go, gcp/vmxenabled.go
We should use the same Linux distribution on the local development environment and host-vm.
We're still using Debian 9 for host-vm. It is a stable version, but most of the package versions are older than Ubuntu 18.04.
=> Replace vmx-enabled base OS with Ubuntu 18.04

artifacts.go, etc/pod-security-policy.yml
In addition, remove `seccomp.security.alpha.kubernetes.io/*` annotations
from PodSecurityPolicies because `docker/default` was deprecated as of
Kubernetes 1.11.
=> Update CKE and coil

pkg/generate-sabakan-machines/main.go
Registration of number of machines is expects huge when we deploy
a new datacenter or a new 3-rack set.
This command supports to generate the machines.json for `sabakan machines create -f`
=> Add a new command generate-sabakan-machines

.circleci/config.yml, bin/run-dctest-suite.sh, bin/run-dctest.sh
Integrate the 2 scripts(`bin/run-dctest.sh`, `bin/run-dctest-release.sh`) into `bin/run-dctest.sh`.
But `bin/run-dctest-release.sh` is not deleted because it is still used in neco-apps.
=> Integrate scripts for CircleCI

progs/cke/templates.go, progs/etcdpasswd/conf.go, progs/sabakan/template.go, progs/vault/templates.go
When boot server restarts, etcd required systemd services might be
failed to start because etcd cluster in the boot server is not yet ready.
Ref: https://circleci.com/gh/cybozu-go/neco/5858
To solve the problem, add etcd-container.service to `Wants=` and `After=`, and extend restart interval `RestartSec=`
=> [systemd] Add etcd-container.service to Wants=, After=

gcp/hostvm.go
Copy /home/. to /mnt using cp rather than Go implementation.
=> [gcp] Fix home directory is not owned by login user

artifacts.go, ignitions/common/systemd/setup-hw.service, progs/setuphw/templates.go
/var/lib/setup-hw should be mounted to the same directory
on the host to create `no-reset` file.
=> Update setup-hw to 1.6.8

etc/cke-template.yml
Current K8s cluster already has etcd alert rules. and the cke-etcd DB
usage is:
- `etcd_mvcc_db_total_size_in_bytes`: 1.7GB
- `etcd_mvcc_db_total_size_in_use_in_bytes`: 1.2GB
Even current k8s cluster is stable, `etcd_mvcc_db_total_size_in_use_in_bytes` is
about 1.2GB and is exceeded 50% of `etcd_server_quota_backend_bytes`
2GB. It would be increased when new worker nodes are added and k8s workloads
are increased. We assume DB usage increases and should not be alerted by AlertManager.
=> [cke] Increase quota DB size

updater/github.go
It did not trim prefix such as "release-".
=> updater: fix ReleaseClient.GetLatestReleaseTag

debian/DEBIAN/postinst
=> Enable bash completion for argocd

etc/squid.yml, etc/unbound.yml
This pull request made the following changes.
- remove `k8s-app` label for squid and unbound because the deletion does not affect to `network-policy` anymore.
=> remove unncessary lables

Makefile.tools
Argo CD v1.2 supports Kustomize v3.1.0, but `kubectl apply -k` doesn't support the version.
As an alternative, we can use kustomize v3.1.0 with the following command:
`kustomize build <dir> | kubectl apply -f -`
=> Add kustomize command to neco

gcp/config.go
as we have more and more data.
=> gcp: enlarge home disk size from 20GB to 50GB

artifacts.go, gcp/artifacts.go
- go: update to 1.12.10.
- placemat: update to 1.3.8.
- CoreOS: udpate to 2191.5.0 as same as artifacts.go.
=> gcp: Update software

artifacts.go, dctest/squid.go, dctest/unbound.go, etc/squid.yml, etc/unbound.yml
To ensure redundancy for `squid` and  `unbound` in case of that more than one pod of them are located in a node and the node is drained, this pull request made the following changes.
- add PodDisruptionBudget for `squid` and  `unbound` deployment.
=> Add PodDisruptionBudget for squid and unbound

artifacts.go, pkg/git-neco/cmd/draft.go
Sometimes `git neco draft` or `git neco review` fails to connect a new PR with ZenHub.
It seems GitHub API may need some time before reporting new PRs.
```console
$ git neco review 591
Draft pull request is not found.  Creating a new pull request...
cybozu-go/neco#591: Set higher priority to Pods with TopoLVM volumes
Is this ok? [y/N]: y
Counting objects: 4, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 974 bytes | 974.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote:
remote: Create a pull request for 'priority' on GitHub by visiting:
remote:      https://github.com/cybozu-go/topolvm/pull/new/priority
remote:
To ssh://g/cybozu-go/topolvm
* …
```
=> git-neco: wait for PR creation

etc/squid.yml
squid's shutdown_time is 30 sec by default,
But pod's terminationGracePeriodSeconds is also 30 sec.
This sometimes causes problems.
To prevent it, change this value to 10 sec.
=> squid: Decrease shutdown_time

Makefile.tools, artifacts.go, ignitions/common/files/etc/k8s-containerd/config.toml, ignitions/common/files/opt/sbin/setup-containerd, ignitions/common/systemd/k8s-containerd.service
Update containerd to 1.3.2.
[containerd 1.3.0](https://github.com/containerd/containerd/releases/tag/v1.3.0) [fixed a bug of ingest corruption](https://github.com/containerd/containerd/pull/3160), which causes instability of [neco-apps](https://github.com/cybozu-go/neco-apps) CI.
=> Update containerd to 1.3.2.

dctest/ignitions.go, dctest/suites.go, ignitions/roles/ss/files/etc/systemd/system/sabakan-cryptsetup.d/mkdir.conf, ignitions/roles/ss/files/etc/udev/crypt-base-path, ignitions/roles/ss/files/etc/udev/rules.d/99-neco.rules, ignitions/roles/ss/site.yml
For storage servers, add by-path based name for encrypted devices using `udev`.
- Add a udev rule file on `/etc/udev/rules.d/99-neco.rules`.
- When encrypted devices appear, add a symlink to `/dev/crypt-disk/by-path`.
- Add a script that called by udev rules.
=> ignitions: Add by-path based name for encrypted devices

.circleci/config.yml, docs/donload-binaries.md, pkg/download-binaries/main.go
- Add `download-binaries` command.
- Add the job to download `kubectl` and `argocd` on the directory for GHR.
=> add download-binaries command

ignitions/roles/ss/files/etc/udev/rules.d/99-neco.rules, ignitions/roles/ss/files/opt/sbin/setup-partition
Create partitions using `gdisk` instead of `parted`.
The partitions created by parted isn't recognized properly. It would come from a bug in parted
that can't handle 4KB sector properly. Let's use gdisk and kpartx instead.
=> Fix setup-partition

dctest/cke.go, dctest/sabakan_state_setter.go, dctest/suites.go
In #874, SS servers were increased. However, as our upgrade test is relying on the previously released neco which is not increasing SS server yet, so, to pass CI, #874 intentionally keeps setting the number of available nodes as 7 in our upgrade test.
This will cause CI error, once #874 is merged to the release branch.
See [this](https://bozuman.cybozu.com/k/#/space/3801/thread/38010/2308422/3141610).
=> Update upgrade test for increasing SS servers

artifacts.go, artifacts_ignore.yaml
etcd v3.3.21.1 has [a critical bug](https://github.com/etcd-io/etcd/issues/11918). So, this PR is for using etcd v3.3.20.1.
=> ignore etcd v3.3.21

ignitions/common/systemd/udev-trigger.service
Since this unit is invoked only by the timer, it should
have no dependencies including the default ones.
=> Fix udev-trigger.service dependencies

ignitions/common/files/etc/fstab
To make the test pass, caused by the absence of device files under /dev/disk/by-label.
=> ignitions: do not use LABEL= in fstab

pkg/ingress-watcher/cmd/export.go, pkg/ingress-watcher/cmd/push.go, pkg/ingress-watcher/cmd/root.go, pkg/ingress-watcher/metrics/metrics.go, pkg/ingress-watcher/watch/watch.go, pkg/ingress-watcher/watch/watch_test.go
- In push mode, "instance" must be sent as grouping key, not label.
- add "update_time" metrics what indicates last check time.
=> ingress-watcher: pass "instance" as grouping key, not label.

dctest/cke.go, dctest/contents.go
#1070 introduced a regression that ignored the server role ratio parameter
required for neco-apps CI.  This fixes it.
=> dctest: fix to set weights in cke-template.yml properly

Makefile, Makefile.tools
because curl does not retry even with `--retry` option.
=> Use wget to download teleport binaries

Makefile
btrfs-tools package is deprecated and split into btrfs-progs and libbtrfs-dev.
=> setup: On Ubuntu 20.04, install btrfs-progs and libbtrfs-dev instead of btrfs-tools

ignitions/common/files/etc/sysctl.d/60-cybozu.conf
We observe some nodes suffer from high CPU usage and sabakan recognizes them as unhealthy.
This PR sets hung_task_panic to 1 to reboot on such event.
#1103
=> ignitions: set kernel parameter to reboot on kernel hung

.circleci/config.yml
This reverts commit 176fc54a6a3ca02e7fb94350e9242626e20bce5e.
=> Revert "disable upgrade ci job temporarily."

etc/cke-template.yml
IPVS with source-hash (sh) scheduler can eliminate needs for
session persistence.  This work is to prepare Coil v2 Egress
NAT feature.
ref: https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/#ipvs-based-kube-proxy
neco-apps CI with this branch has passed:
https://app.circleci.com/pipelines/github/cybozu-go/neco-apps/3819/workflows/359764da-d3af-4e08-9d7e-5831289cfeb3/jobs/12982
=> kube-proxy: use source-hash scheduling algorithm

docs/neco.md, pkg/neco/cmd/reboot_worker.go
This PR updates `neco reboot-worker` command.
Originally this command reboots worker nodes immediately via IPMI.
CKE now provides the function of graceful reboot, so use that function for the nodes assigned to CKE.
=> reboot-worker: use CKE's graceful reboot functionality for cluster nodes.

dctest/menu-ss.yml
Sometimes, the CI test failed due to a kernel soft lock up crash.
It seems the linux kernel could not allocate enough memory in the watchdog timer interval.
This decreases VM memory size to reduce the possibility of such situation.
=> tuning memory size to avoid the error when CI

bin/run-dctest.sh
If an instance is deleted after listing, this gcloud fails. Prevents CI Error from this error.
=> Ignore gcloud error when adding canceled labels

artifacts.go, etc/coil.yaml, etc/netconf.json, ignitions/common/files/opt/sbin/setup-local-network
Now that Coil detects the optimal MTU value automatically,
tuning plugin is no longer necessary on GCP environment.
=> Update coil to 2.0.3 and remove "tuning" CNI plugin

dctest/menu-ss.yml
Currently, the ss node has only 4G memory, which is not enough to have two OSD pods. 
So, the ss node's memory is returned to 10G.
=> Resize ss node memory size

Makefile
The `tsh` binary for linux is not contained in the CLI deb package.
This PR fixes the code to add the binary to the package.
=> Fix creation logic of deb package to include tsh binary

artifacts.go, pkg/ingress-watcher/cmd/push.go
`ingress-watcher` get stuck when the connection to push-gateway is refused.
This is because the default timeout setting is 0, which means no timeout on the client side.
This PR fixes this behavior. 
=> ingress-watcher: set timeout for pushing metrics

etc/cke-template.yml
"sh" is no longer needed because of https://github.com/cybozu-go/neco-apps/pull/884 .
=> Update kube-proxy mode from sh to rr

artifacts.go, progs/sabakan/upload.go
When fetching an image from ghcr, this error https://app.circleci.com/pipelines/github/cybozu-go/neco-apps/4279/workflows/d34e9d40-15d9-448e-9f70-35a83348aa34/jobs/14796 occurs.
This PR mitigates this failure because this is probably a problem on the ghcr side.
=> Increase retry count to stabilize test

ignitions/common/files/opt/sbin/setup-var, menu/cluster.go, menu/testdata/cluster.yml
=> extend /var/lib/k8s-containerd to avoid disk pressure when testing rook/ceph

dctest/auto-config
to allow cybozu to invoke rkt command.
=> dctest: add rkt group to cybozu

constants.go, dctest/init_test.go, dctest/setup_test.go, ignitions/common/files/opt/sbin/setup-hw, pkg/neco/cmd/bmc_setuphw.go, pkg/neco/cmd/init_local.go, pkg/neco/cmd/teleport_config.go, progs/etcdpasswd/sshd.go, worker/etcdpasswd.go
This PR contains three fixes for recently found problems:
- Install sshd_config under `/etc/ssh/sshd_config.d` directory on Ubuntu 20.04 or later.
- Wait for iDRAC reset before running `setup-hw` utility in `neco bmc setuphw`.
- Remove `neco init-local teleport` sub command.
=> Fixing things

installer/setup/packages.go
fwupd tries to download firmware over the Internet.
This is not possible on boot servers, so we purge it.
=> installer: purge fwupd

pkg/git-neco/cmd/clean.go, pkg/git-neco/cmd/dev.go, pkg/git-neco/cmd/draft.go, pkg/git-neco/cmd/gc.go, pkg/git-neco/cmd/git.go
The default branch name on GitHub has been changed to `main`.
=> git-neco: use default branch instead of `master`

debian/lib/systemd/system/backup-cke-etcd.service, progs/setup-serf-tags/template.go
This bug was introduced when we switched CKE installation
from container to the debian package.
`setup-serf-tags` is also fixed not to ignore the unit failure
so that we can notice the failure.
=> Fix backup-cke-etcd not working

menu/cluster.go, menu/testdata/cluster.yml
placemat-menu references images with branch tags, so
they are updated as follows:
- chrony 4.0
- dnsmasq 2.84
Since `rkt` cannot run the new squid image (`quay.io/cybozu/squid:4`),
it remains 3.5.
=> placemat-menu: update dnsmasq and chrony images

Makefile.common
kustomize 3.9.2 has a critical bug to us.
https://github.com/kubernetes-sigs/kustomize/issues/3489
=> Revert kustomize to 3.7.0

Makefile, Makefile.common, Makefile.tools, artifacts.go
- Add the `kubectl-moco` binary to `neco` and `neco-operation-cli-{linux, windows}` packages.
By this PR, the following files are added to the packages.
```
./usr/bin/kubectl-moco
./usr/share/doc/moco/{LICENSE, README.md}
```
```
./bin/kubectl-moco.exe
./doc/moco/{LICENSE, README.md}
```
- Change the directory structure of the `neco-operation-cli-windows` zip file as follows.
```
./bin/{argocd.exe, kubectl.exe, kubectl-moco.exe, stern.exe, tsh.exe}
./doc/argocd/{LICENSE, README.md}
./doc/kubectl/{LICENSE, README.md}
./doc/moco/{LICENSE, README.md}
./doc/stern/{LICENSE, README.md}
./doc/teleport/{LICENSE, README.md}
```
=> Add kubectl-moco

Makefile.common, Makefile.tools
Update `kubectl-moco` to v0.6.0 in neco tools packages.
I build locally and verified that the `kubectl-moco` is updated.
=> Update kubectl-moco v0.6.0

dctest/Makefile
=> when dctest cleans, it also deletes the root file

Makefile.common, etc/cke-template.yml
This PR deploys CKE 1.19.5 and adds audit log settings.
It should be merged after the `manual-dctest-with-neco-feature-branch` test succeeds on neco-apps.
-> The test on the feature branch succeeded. Now this PR is ready.
=> Enable audit log settings

pkg/sabakan-state-setter/config.go, pkg/sabakan-state-setter/config_test.go, pkg/sabakan-state-setter/controller.go, pkg/sabakan-state-setter/controller_test.go, pkg/sabakan-state-setter/machine_state_source.go, pkg/sabakan-state-setter/sabakan.go, pkg/sabakan-state-setter/sabakan_mock.go, pkg/sabakan-state-setter/serf.go, pkg/sabakan-state-setter/serf_mock.go, pkg/sabakan-state-setter/strategy.go, pkg/sabakan-state-setter/strategy_test.go
sabakan-state-setter uses `serf.Member` and the result value of Sabakan GraphQL directly.
For that reason, the implementation is becoming more complicated in some places.
This PR changes the clients (`SabakanGQLClient` and `SerfClient`) to return only the values sabakan-state-setter needs.
And for https://github.com/cybozu-go/neco/issues/675, I change the GraphQL request to get the status and the BMC address of a machine.
=> Fix clients for sabakan-state-setter

dctest/cke_test.go, dctest/upgrade_test.go
Fix the following flaky test.
https://app.circleci.com/pipelines/github/cybozu-go/neco/4426/workflows/40521746-f25f-41b8-96ca-fbb088204d13/jobs/13514
```
------------------------------
Neco upgrade 
should running newer cke desired image version
/root/go/src/github.com/cybozu-go/neco/dctest/upgrade_test.go:156
START: 2021-04-05T05:19:42Z
STEP: generating kubeconfig for cluster admin
END: 2021-04-05T05:19:47Z
• Failure [5.205 seconds]
Neco
/root/go/src/github.com/cybozu-go/neco/dctest/suites_test.go:35
upgrade
/root/go/src/github.com/cybozu-go/neco/dctest/suites_test.go:91
should running newer cke desired image version [It]
/root/go/src/github.com/cybozu-go/neco/dctest/upgrade_test.go:156
[10.72.48.0] [ckecli kubernetes issue > .kube/config]: 2021-04-05T05:19:47.506232Z gcp0-boot-0 ckecli …
```
=> eventually ckecli kubenetes issue

go.mod, go.sum, pkg/neco/cmd/power.go, pkg/neco/cmd/reboot_and_wait.go, pkg/neco/cmd/reboot_worker.go
Refine `neco power` command using Redfish API.
`start`, `stop` or `restart` action.
```
$ neco power stop <addr>
ok
$ neco power start <addr>
2021-04-08T08:41:00.859206Z ubuntu-bionic neco error: "409: {\"error\":{\"@Message.ExtendedInfo\":[{\"Message\":\"Server is already powered ON.\",\"MessageArgs\":[],\"MessageArgs@odata.count\":0,\"MessageId\":\"IDRAC.2.1.PSU501\",\"RelatedProperties\":[],\"RelatedProperties@odata.count\":0,\"Resolution\":\"No response action is required.\",\"Severity\":\"Informational\"}],\"code\":\"Base.1.5.GeneralError\",\"message\":\"A general error has occurred. See ExtendedInfo for more information\"}}\n"
```
`status` action
```
$ neco power status <addr>
On
$ neco power status <addr>
Off
```
=> Refine 'neco power' command using Redfish API

installer/setup/packages.go
Now that "neco power" does not depend on IPMI.
=> installer: do not install freeipmi-tools

artifacts.go, docs/neco.md, pkg/neco/cmd/power.go, pkg/neco/cmd/reboot_worker.go
`neco reboot-worker` will fail if there are machines powered off.
=> neco reboot-worker: skip reboot if machine power is already off

artifacts.go, docs/neco.md, pkg/neco/cmd/tpm_clear.go, pkg/sabakan-state-setter/controller.go, pkg/sabakan-state-setter/controller_test.go, pkg/sabakan-state-setter/necocommand.go, pkg/sabakan-state-setter/necocommand_mock.go
- Add safety features to `neco tpm clear`. (same as [`sabactl crypts delete`](https://github.com/cybozu-go/sabakan/blob/main/docs/sabactl.md#sabactl-crypts-delete-serial))
- The command fails when the target machine's status is not `Retiring`.
- The command fails when `--force` option is not specified.
- Output failure messages of `neco tpm clear` in the sabakan-state-setter log.
=> Add safety features to 'neco tpm clear'

dctest/retire_test.go, dctest/sabakan_state_setter_test.go, docs/sabakan-state-setter.md, etc/sabakan-state-setter.yml, go.mod, go.sum, pkg/sabakan-state-setter/config.go, pkg/sabakan-state-setter/config_test.go, pkg/sabakan-state-setter/controller.go, pkg/sabakan-state-setter/controller_test.go, pkg/sabakan-state-setter/necocommand.go, pkg/sabakan-state-setter/necocommand_mock.go, pkg/sabakan-state-setter/sabakan.go, pkg/sabakan-state-setter/sabakan_mock.go
Add a new feature to `sabakan-state-setter` to auto shutdown retired machines.
When this change is released, the retired machines will be shut down at 1:00 AM (JST) every day.
=> sabakan-state-setter: shutdown retired machines

artifacts.go, etc/coil.yaml, ignitions/common/files/etc/sysctl.d/70-cybozu.conf
Programs that use Ceph RBD block device can hang longer than
120 seconds, and let the kernel panic because of this setting.
Disable it to prevent panics at least for now.
=> ignitions: disable kernel.hung_task_panic

etc/cke-template.yml
This feature gate enables TTL controller for expired Jobs.
https://v1-19.docs.kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
=> Enable TTLAfterFinished feature gate

dctest/upgrade_test.go
As `neco-updater` problem was fixed, temporary code to pass upgrade test is not necessary anymore.
So, this PR deletes the code
=> Remove temporary code

generator/generate.go
Implemented #1536 
Old CoreOSFeed URL("https://www.flatcar-linux.org/releases-json/releases-stable.json") doesn't contain the new release version.
So I replace with proper URL ("https://kinvolk.io/flatcar-container-linux/releases-json/releases-stable.json").
This URL is found in "https://kinvolk.io/flatcar-container-linux/releases/"
=> generate-artifacts: replace flatcar-release url with the proper one

docs/neco.md, etc/cke-template.yml, pkg/neco/cmd/apply-firmware.go
part of https://github.com/cybozu-go/neco/issues/1577
1. upload firmware updaters to sabakan as assets
2. run setup-apply-firmware on each worker
3. schedule reboot
=> add `neco apply-firmware` command

docs/neco.md, pkg/neco/cmd/apply-firmware.go, pkg/neco/cmd/isoreboot.go
part of https://github.com/cybozu-go/neco/issues/1578
1. upload the iso file as a asset
2. run setup-isoreboot on each worker
3. schedule reboot
=> add `neco isoreboot` subcommand

etc/cke-template.yml
This PR records all the k8s events in the audit log.
They are recorded using `create` and `patch` verbs; read and delete operations of the events are not recorded.
=> Record all k8s events in the audit log

dctest/menu-ss.yml, dctest/menu.yml
Modify the IP settings of dctest to be the same as stage-0 because it does not match the GlobalNetWorkPolicy settings.
[manual-dctest-with-neco-feature-branch](https://app.circleci.com/pipelines/github/cybozu-go/neco-apps/6520/workflows/f6bd8b6f-16ad-47e8-9a23-8e1b3ca3dc9c/jobs/22047) passed
=> Modify the IP settings of dctest

Makefile.common
Update CKE to 1.20.3.
It triggers upgrade of the etcd cluster for k8s to v3.4.16.
=> Update CKE to 1.20.3

dctest/cke_test.go, dctest/reboot_test.go, dctest/setup_test.go, dctest/upgrade_test.go
`kubectl` is sometimes very slow due to its caching.
To speed it up, this PR mounts `.kube` directory by tmpfs.
This PR was tested with neco-apps [here](https://app.circleci.com/pipelines/github/cybozu-go/neco-apps/6509/workflows/3c5f6877-5651-4145-a6e8-78db8f2ccf26).
=> Mount .kube directory by tmpfs

etc/cke-template.yml
Due to the lease timeout, `controller-manager` and `kube-scheduler` sometimes become unstable.
To fix this issue, this PR modified the related flags listed below
- `--leader-elect-retry-period`
- `--leader-elect-renew-deadline`
- `--leader-elect-lease-duration`
Also, as the etcd-rivers and rivers are connecting to the unhealthy api-server due to the long health check interval,  this PR shortened the interval too.
=> Extend lease params for kube-scheduler and controller-manager

ignitions/common/files/etc/fstab, ignitions/common/files/opt/sbin/setup-var
part of https://github.com/cybozu-go/neco/issues/1647
- bind mount
- always re-mkfs /var/lib/kubelet to make it "volatile"
=> bind mount /var/log to /var/lib/kubelet/varlog

dctest/menu-ss.yml, ignitions/common/files/opt/sbin/setup-var
part of https://github.com/cybozu-go/neco/issues/1647
increase kubelet LV size to increase ephemeral storage capacity.
=> increase number of disks and kubelet LV size on dctest

ignitions/common/files/etc/sysctl.d/70-cybozu.conf
part of https://github.com/cybozu-go/neco/issues/1677
This PR solves the problem that systemd-coredump does not retrieve the correct process information.
Use the default value of kernel.core_pattern, which is set by /usr/lib/sysctl.d/50-coredump.conf
=> fix kernel.core_pattern in sysctl

dctest/run_test.go, setup/etcd_backup.go
This PR removes `ETCDCTL_API=3`, that becomes default on etcd 3.4.
=> remove ETCDCTL_API variable

ignitions/common/common.yml, ignitions/common/files/etc/sysctl.d/70-cybozu.conf, ignitions/common/files/etc/systemd/system/sys-kernel-tracing.mount.d/mode.conf
part of https://github.com/cybozu-go/neco/issues/1694
- set `kernel.perf_event_paranoid` sysctl to `1`
- ~remount~ mount /sys/kernel/tracing with mode=755
=> change settings for non-privilege users to use perf

docs/etcd.md, docs/update.md, pkg/neco/cmd/recover.go, storage/keys.go, storage/storage.go, storage/storage_test.go, worker/worker_test.go
part of https://github.com/cybozu-go/neco/issues/1727
=> follow `neco recover` behavior to current neco-worker process.

progs/cke/conf.go, progs/cke/conf_test.go
This PR makes reboot follow only the PDBs on the namespaces:
- one does not have `development` label at all, or
- one has `development` label but its value is not `"true"`.
It is mandatory to merge cybozu-go/neco-apps#1721 in advance.
=> Ignore PDBs on developmental namespaces on reboot 

debian/etc/systemd/system/systemd-pstore.service.d/after-local-fs-mount.conf, ignitions/common/common.yml, ignitions/common/files/etc/systemd/system/systemd-pstore.service.d/after-local-fs-mount.conf
In some environment, systemd-pstore.service run **before** /sys/fs/pstore is mounted. I doesn't make sense.
=> make systemd-pstore run after mounting pstore

dctest/menu-ss.yml, dctest/menu.yml
Aligned the IP addresses of the network equipment in the Neco staging environment with the IP addresses of the network equipment in the dctest environment.
- Wanted to run some tests on network equipment with neco-apps.
- The IP address for neco's staging network equipment is `10.72.0.0/20`.
=> Fix ip of network equipment

artifacts_ignore.yaml
Ignore Coil v2.0.12 because it doesn't work with Neco environment.
=> Ignore coil 2.0.12

pkg/neco/cmd/power.go, pkg/neco/cmd/tpm_clear.go, pkg/sabakan-state-setter/controller.go
https://github.com/cybozu-go/neco/issues/1803
- Use `ForceOff` in `neco power stop`.
- Power off if clearing TPM is not supported in `neco tpm clear`.
- Output the result of `neco` command from `sabakan-state-setter`.
=> Improve power management of retired/retiring machines

Makefile.common, go.mod, go.sum
New CKE will deploy Kubernetes 1.21.6.
=> Update CKE to 1.21.1

artifacts.go, generator/generate.go
The new version is 2983.2.0 that brings a lot of changes
including cgroup v2 and cryptsetup 2.3.6 and Intel E800 driver.
=> Update Flatcar release JSON URL and flatcar version

Makefile.tools
- When executing wget, 503 status codes were returned from the download destination, and `make -f Makefile.tools` often failed.
- Fixed to retry wget when a 503 status code comes back.
#1817 
=> Add '--retry-on-http-error=503' to wget options

ignitions/common/common.yml, ignitions/common/files/opt/sbin/chrony-monitor, ignitions/common/systemd/chrony-monitor.service, ignitions/common/systemd/chrony-monitor.timer, ignitions/common/systemd/node-exporter.service
This PR exports chrony metrics using Textfile Collector provided by node_exporter.
1. Add `chrony-monitor.service` and `chrony-monitor.timer` that periodically writes chrony metrics to `/var/lib/textfile-collector`.
The metrics file should be written atomically.
https://github.com/prometheus/node_exporter#textfile-collector
2. Add to node_exporter `--collector.textfile.directory` option to enable Textfile Collector.
=> Export chrony metrics

ignitions/common/files/opt/sbin/chrony-monitor
Rename `chrony_monitor_tracking_system_time` to `chrony_monitor_tracking_system_time_seconds`
=> Fix chrony metrics name

ignitions/common/systemd/chrony-monitor.service, ignitions/common/systemd/chrony-monitor.timer
Previously, `chrony-monitor.service` did not run after `chrony-wait.service`.
This PR fixes the order.
=> Run chrony-monitor.timer after chrony-wait.service

dctest/retire_test.go
=> Use delete-emptydir-data option instead of deprecated delete-local-data

dctest/unbound_test.go
=> insert double dash before remote command of `kubectl exec`

artifacts.go, cilium/upstream.yaml, cilium/values.yaml, dctest/cilium_test.go, etc/cilium.yaml
This PR enables TLS for the communication between hubble-relay and clients such as hubble-cli and hubble-ui-backend. Also it updates flatcar.
=> Enable hubble server tls

cilium/kustomization.yaml, cilium/pdb.yaml, cilium/upstream.yaml, cilium/values.yaml, etc/cilium.yaml
This PR adds PDB and resource requests for hubble-relay and cilium-operator. Cilium's helm chart doesn't add PDB because of https://github.com/cilium/cilium/issues/18303. We will remove the PDB manifest once the fix would be released.
=> Modify cilium setting to add PDB and resource settings

cilium/upstream.yaml, cilium/values.yaml, etc/cilium.yaml
EnableIdentityMark needs to be disabled to avoid conflicting identity marks when Cilium is configured with CNI-chaining.
https://github.com/cilium/cilium/blob/bcb2db046b49dede753f91799552f31ec687f7e0/pkg/option/config.go#L303
=> Set enableIdentityMark false

ignitions/common/common.yml, ignitions/common/files/etc/systemd/networkd.conf.d/01-cybozu.conf
Networkd drops foreign routing policy rules by default from systemd v248.
https://github.com/systemd/systemd/commit/0b81225e5791f660506f7db0ab88078cf296b771
We need to set ManageForeignRoutingPolicyRules=no and ManageForeignRoutes=no to protect foreign routing policy rules, otherwise networkd drops the rules created by Coil and Cilium. It leads to network disruption when one of the underlying interfaces on a node goes down.
=> Set ManageForeignRoutingPolicyRules and ManageForeignRoutes no

artifacts.go, etc/cke-template.yml
Workaround for https://github.com/cilium/cilium/issues/18819
Confirmed reboot and manual-dctest-with-neco-feature-branch have passed.
https://app.circleci.com/pipelines/github/cybozu-go/neco-apps?branch=add-boot-taints-cilium&filter=all
=> Add node.cilium.io/agent-not-ready taint

dctest/boot-seed.yml.template
This is to avoid conflicts with dctest's kubeconfig.
=> Export kubeconfig to a separate file

Makefile, dctest/ignitions_test.go, ignitions/roles/cs/files/opt/sbin/update-neco-operation-cli, ignitions/roles/cs/site.yml, ignitions/roles/cs/systemd/update-neco-operation-cli.service, ignitions/roles/cs/systemd/update-neco-operation-cli.timer
This commit enables distribution of Neco operation CLI commands
via Sabakan to worker nodes.
The distributed commands are to be used by Teleport node Pods.
=> Distribute Neco operation CLI commands for Teleport

etc/cke-template.yml, ignitions/common/common.yml, ignitions/common/systemd/remove-kubelet-state.service
part of https://github.com/cybozu-go/neco/issues/1684
- change CPU manager policy to `static`
- reserve some CPUs for system
- remove kubelet state files before it starts
=> enable cpu pinning

progs/etcd/templates.go
etcd 3.5.[0-2] has data inconsistency issue.
https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ
=> Enable `experimental-initial-corrupt-check` for etcd

artifacts.go, artifacts_ignore.yaml, cilium/upstream.yaml, cilium/values.yaml, etc/cilium.yaml
This PR includes
- Update cilium to 1.11.3
- Set PolicyAuditMode false
Cilium v1.11.3 helm chart hasn't supported certgen v0.1.8. So ignore it for now.
=> Update cilium to 1.11.3

dctest/ignitions_test.go, ignitions/common/files/opt/sbin/setup-var, ignitions/roles/ss/files/etc/udev/rules.d/99-neco.rules
Confirmed that neco-apps reboot suite(make dctest-reboot SUITE=prepare) has passed in my environment.
FYI, bootstrap-with-neco-branch has also passsed.
https://app.circleci.com/pipelines/github/cybozu-go/neco-apps/9829/workflows/c3c9f2d5-b7e6-4f54-996f-037c23ddc88f/jobs/33230
=> Add crypt-vdc to udev rule

.circleci/config.yml, Makefile, cilium/upstream.yaml, coil/kustomization.yaml, etc/cilium.yaml, etc/coil.yaml
Check auto-generated files in CI. And re-generate manifests.
1. The API version of CronJob in cillium manifests are changed from `batch/v1beta1` to `batch/v1` with the upgrade of the helm command.
The API version is changed by the build-in parameter  (`.Capabilities.KubeVersion.Version`) of the helm command.
https://github.com/cilium/cilium/blob/v1.11.4/install/kubernetes/cilium/templates/hubble/tls-cronjob/cronjob.yaml#L2
https://github.com/cilium/cilium/blob/v1.11.4/install/kubernetes/cilium/templates/_helpers.tpl#L83-L92
2. The coil manifest may be updated manually in the following PR. So I update the source file.
https://github.com/cybozu-go/neco/pull/1980.
=> Check auto-generated files

dctest/squid_test.go, dctest/unbound_test.go, etc/squid.yml, etc/unbound.yml
The policy/v1beta1 PodDisruptionBudget is deprecated. So I use `policy/v1`.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
=> Use policy/v1 PodDisruptionBudget

artifacts.go, etc/cke-template.yml
part of https://github.com/cybozu-go/neco/issues/1684
enable Topology Manager and die-aware CPU pinning.
=> enable Topology Manager

artifacts.go, progs/promtail/promtail.yaml.tmpl
Update promtail to v2.5.0.
I change the `clients` config instead of the `client` config, in addition to updating the image.
The `client` config seems to be deprecated.
https://github.com/grafana/loki/blob/v2.5.0/clients/pkg/promtail/config/config.go#L22-L24
https://github.com/grafana/loki/pull/536
=> Promtail v2.5.0

bin/watch_podlogs_directly
Currently, there is a script `bin/watch_podlogs` that outputs logs of pods in a cluster via GCP. 
However, I wanted a script that directly outputs logs of pods in a cluster without via GCP, so I created a new script.
=> Add script for watch podlogs without via GCP

Makefile, Makefile.tools
Add hubble, jsonnet, jsonnetfmt and kustomize to neco-operation-cli.
Remove cillium-cli from neco-operation-cli.
=> Add some CLI to neco-operation-cli

etc/squid.yml, etc/unbound.yml
part of https://github.com/cybozu-go/neco/issues/2036
The original manifest has soft inter-rack distribution. However, multiple replicas can run on same node and their eviction will fail due to its corresponding PDB. Hard inter-node distribution should be configured.
=> node-distribute internet-egress Pods

artifacts_ignore.yaml
Ignore Flatcar 3227.2.0 temporarily until we finish the operation for L4LB.
=> Ignore flatcar 3227.2.0 temporarily

dctest/unbound_test.go, etc/sabakan-state-setter.yml
Extended the time to become Unhealthy from the default of 1 hour to 2 hours.
This is because we wanted time to maintain our network equipment.
=> Extend grace-priod to 2h

cilium/pre/upstream.yaml, cilium/pre/values.yaml, etc/cilium-pre.yaml
I changed `cilium-pre.yaml` to enable XDP acceleration for dctest and stage.
=> enable xdp acceleration

cilium/pre/upstream.yaml, cilium/pre/values.yaml, etc/cilium-pre.yaml
Reverts cybozu-go/neco#2063. The XDP acceleration will be applied after the k8s upgrade is released to be on the safe side. Releasing both can make our trouble shooting harder.
=> Revert "enable xdp acceleration"

artifacts.go, ignition-template/settings.json, ignitions/common/common-gcp0.yml, ignitions/common/common-stage0.yml, ignitions/common/files/etc/k8s-containerd/conf.d/docker.elastic.co/hosts.toml
Add setting to enable docker.elastic.co registry mirror.
Signed-off-by: Taichi Takemura [taichi-takemura@cybozu.co.jp](mailto:taichi-takemura@cybozu.co.jp)
=> Enable registry mirror

progs/etcd/templates.go
This mitigates the rapid increase of etcd's storage consumption
on the boot servers, which is caused by frequent DHCP requests
from unconfigured servers.
=> Increase rate of etcd auto-compaction on boot servers

debian/usr/sbin/kill-old-login-sessions
Sometimes, kill-old-login-sessions.service is failed with the following error.
It seems that a session may disappear immediately after listing session IDs.
This PR ignores the error.
```
$ journalctl -u kill-old-login-sessions.service
-- Logs begin at Wed 2022-09-14 23:08:01 UTC, end at Thu 2022-09-15 07:20:54 UTC. --
Sep 15 00:00:00 gcp0-boot-2 systemd[1]: Starting kill old login sessions...
Sep 15 00:00:01 gcp0-boot-2 kill-old-login-sessions[57632]: Failed to get session path: No session '42' known
Sep 15 00:00:01 gcp0-boot-2 systemd[1]: kill-old-login-sessions.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 00:00:01 gcp0-boot-2 systemd[1]: kill-old-login-sessions.service: Failed with result 'exit-code'.
Sep 15 00:00:01 gcp0-boot-2 systemd[1]: Failed to start kill old …
```
=> Ignore error in kill-old-login-sessions

dctest/before_test.go, ignitions/common/files/opt/sbin/setup-serf-conf, ignitions/common/systemd/setup-serf-tags.timer, progs/serf/conf.go, progs/serf/conf_test.go, progs/serf/templates.go, worker/setup_serf_tags.go
Serf fails to update tags without a longer broadcast timeout in a large cluster.
https://github.com/hashicorp/consul/issues/8435
This PR extends the timeout to one minute.
=> serf: Set broadcast timeout to one minute

cilium/pre/configmap.yaml, cilium/pre/kustomization.yaml, cilium/prod/configmap.yaml, cilium/prod/kustomization.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
This PR extends CT lifetimes for non-tcp connections to fix an issue that long-life connections through coil-egress nat are disrupted. 
It seems that Cilium helm chart doesn't support bpf-ct-timeout-*, so I patched the cilium-config cm generated with `helm template` instead. We need to restart cilium-agent manually because the check-sum in the cilium ds manifest is not modified.
=> Extend CT lifetimes for non-TCP

cilium/pre/configmap.yaml, cilium/pre/kustomization.yaml, cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/configmap.yaml, cilium/prod/kustomization.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
This PR sets bpf-ct-timeout* using extraConfig instead of the cm patch.
https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium
=> Use extraConfig

dctest/dcscp, dctest/dcssh
We cannot use `dcssh` and `dcscp` unless the current working directory is `/path/to/neco/dctest` since the ssh config that these tools use requires the identity file `dctest_key` exists in the current working directory. This commit changes `dcssh` and `dcscp` to pass the absolute path of `dctest_key` to an inner ssh command so that these scripts can be run from everywhere.
=> dctest: dcssh: pass identify file path via command line option

cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
- Update values.yaml for Cilium Chart
- Add `bpf.policyMapMax: 65536`
- Build manifests
- Run `make update-cilium CILIUM_PRE=true` and `make update-cilium`
=> Extend bpf-policy-map-max to 65536

dctest/Makefile, generator/generate.go, github.go, pkg/download-neco-deb/main.go, pkg/find-installed-release/main.go, updater/github.go, updater/release_checker.go, updater/server.go, worker/deb.go, worker/operator.go
I updated `download-neco-deb` commnad to read PAT from GITHUB_TOKEN environment variable.
Also updated `find-installed-release` too.
=> Use GITHUB_TOKEN when downloading deb file

updater/github_test.go
Tests in github_test.go was disabled.
We create a dedicated repo for the tests and enable them.
=> enable github release/tag related tests

Makefile, cilium/pre/upstream.yaml, cilium/pre/values.yaml, etc/cilium-pre.yaml
The update-cilium target retrieves Cilium v1.12.4 source code, patch 18449, and renders Cilium manifest with it because patch 18449 contains modifications for the helm chart.
https://github.com/cilium/cilium/compare/v1.12.4...ysksuzuki:cilium:v1.12.4-with-18449
=> Enable LB IPIP CNI mode on staging

artifacts.go, cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
The cgroup v2 auto-mount is no longer needed because the cgroup v2 has been enabled in our worker nodes.
https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#kubeproxy-free
> Cilium will automatically mount cgroup v2 filesystem required to attach BPF cgroup programs by default at the path /run/cilium/cgroupv2. To do that, it needs to mount the host /proc inside an init container launched by the DaemonSet temporarily. If you need to disable the auto-mount, specify --set cgroup.autoMount.enabled=false, and set the host mount point where cgroup v2 filesystem is already mounted by using --set cgroup.hostRoot. For example, if not already mounted, you can mount cgroup v2 filesystem by running the below command on the host, and specify --set cgroup.hostRoot=/sys/fs/cgroup.
=> Disable the cgroup v2 auto-mount

README.md, constants.go, dctest/Makefile, dctest/menu-ss.yml, dctest/menu.yml, installer/Makefile, installer/README.md, installer/autoinstall/user-data, installer/customize-cloud-image, installer/patch/grub.cfg, installer/setup/docker.go
- Update ISO/QEMU custom installer for the boot server to Ubuntu 22.04
- Updated OS image used by dctest to Ubuntu22.04
=> Update Ubuntu from 20.04 to 22.04

dctest/sabakan_state_setter_test.go
By default, dctest starts with 3 racks.
When we would like to increase the number of racks, the status check for boot servers in added racks fails and prevents the start up proess.
In this PR, the boot server status check is skipped for racks whose rack ID is over 2.
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
Co-authored-by: ESASHIKA Kaoru <kaoru-esashika@cybozu.co.jp>
=> Skip boot server status check in dctest whose rack ID is over 2

artifacts_ignore.yaml, installer/Makefile
`installer/Makefile` downloads a libssl package with a hard-coded
URL.
This URL has been changed due to security update.
See https://packages.ubuntu.com/jammy/amd64/libssl3/download for
the new URL.
=> installer: Update libssl package used in initial setup

debian/etc/profile.d/loki-env.sh
step1 part of https://github.com/cybozu-go/neco/issues/2214
- `LOKI_ADDR` points the loki in logging NS.
- `LOKI_ORG_ID` is `fake`, the default org-id that a single-tenant loki uses.
see also https://github.com/cybozu/neco-containers/pull/968
=> add support env vars for logcli

.circleci/config.yml
The default compression type of dpkg-deb 1.21.1 is zstd,
It doesn't work concurrently and leads to the timout error
This PR workaround this issue by spcifiying -zxz explicitly
=> Fix slow deb package build issue

etc/cke-template.yml
This parameter probably solve performance issues.
ref. https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
=> Increase controller-manager's QPS to use while talking with apiserver

bin/run-dctest-suite.sh
This reverts commit 0e91abab32cab4712460afbd5947d2606cde2305.
Re-run was necessary to upgrade Ginkgo from V1 to V2.
The next upgrade from V2 to V3 will not occur for a while.
=> Revert "ci: Re-run setup to upgrade Ginkgo"

progs/promtail/promtail.yaml.tmpl
part of https://github.com/cybozu-go/neco/issues/2214
=> add org-id (tenant-id) option to loki clients

dctest/reboot_test.go
test `neco reboot-worker`'s queueing behavior with:
- without options
- with `--role=cs`
- with `--role=ss`
see also: https://github.com/cybozu-go/neco/pull/2247
=> test neco reboot-worker for each role

dctest/setup_test.go, pkg/neco/cmd/setup.go, setup/setup.go
The neco-updater process sometimes aborts due to the API rate limit exceeded error in the bootstrap test. (That occurs in certain bare-metal servers). This PR set a gh token for neco-worker in the neco setup command to avoid the error using the GitHub PAT located in the neco repository(github-token file).
=> Set GitHub Token for bootstrap test

artifacts.go, artifacts_ignore.yaml, cilium/pre/upstream.yaml, cilium/prod/upstream.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
We can't upgrade cilium and squid at the same time. Let's upgrade squid separately
- Fail to start squid pod because cilium hasn't started yet
- Fail to pull new cilium image because squid hasn't started yet
- Communication through the node port svc(squid svc) fail because cilium can't update the bpf map
=> Upgrade Cilium to 1.12.8

etc/cke-template.yml
CKE 1.25.1 introduces a configuration parameter `.reboot.command_retries`
for the reboot queue.
This commit specifies the parameter to issue the reboot command for
6 times.
This may suspend CKE's reconciliation for up to 180 seconds.
=> Configure CKE to retry reboot command

ignitions/common/files/etc/bird/bird.conf, installer/setup/templates.go
This commit updates the BIRD configuration to extend the BFD TX/RX intervals
from 300 ms to 400 ms.
The multiplier is set to 5 in default.
This combination means that a link is not declared as down if the link
failure is shorter than 2 sec.
In other words, the detection of the link failure is delayed by 2 sec.
This commit also shorten the minimum delay between a protocol failure
and automatic restart for the BGP protocols from 60 sec (default) to
3 sec.
This will speed up the recovery from a failure.
See https://bird.network.cz/?get_doc&v=20&f=bird-6.html#ss6.2 for the BFD parameters.
See https://bird.network.cz/?get_doc&v=20&f=bird-6.html#ss6.3 for the BGP parameters.
=> Refine BIRD configuration parameters

cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
We've remove the scrape config for the hubble metrics. So let's disable the hubble metrics for now.
=> Disable hubble metrics

debian/lib/systemd/system/docker-prune.service, ignitions/common/systemd/docker-prune.service
This commit extends the lifetimes of docker containers and images
from 3 days to 7 days.
This will save containers/images from deletion even if the server
is inactive for several days.
Note that we cannot use the notation of "7d" nor "1w" because
Docker employs Go duration strings.
=> Extend lifetimes of docker containers and images

artifacts_ignore.yaml
Hold off on Cilium updates until squid 5.8.0 is released, since we can't upgrade Cilium and squid at the same time
https://github.com/cybozu-go/neco/pull/2301
=> Ignore Cilium 1.12.10

installer/Makefile
workaround for the environment which is detected "not 22.04"
=> update libssl3 package url for installer

Makefile.common
Update Argo CD to 2.6.8 from 2.6.7
=> update argocd to ver 2.6.8

Makefile, artifacts_ignore.yaml
This pr fixes CI failures by using removed file: `github.com/cybozu/neco-containers/cilium/18449.patch`.
To avoid this, I changed to use the old commit hash of neco-containers.
https://github.com/cybozu/neco-containers/blob/bafee04577033ed384add6152b016c04d2ffd55d/cilium/18449.patch
Also, this creates `artifacts_ignore.yaml` to ignore newer cilium related images.
=> Fix to use the old commit hash of neco-containers in make update-cilium target

docs/ignition.md, ignition-template/settings.json, ignitions/common/common.yml, ignitions/common/files/opt/sbin/reset-iscsiuio, ignitions/common/systemd/reset-iscsiuio.service
This PR:
- masks `iscsiuio.service` because it is not used
- resets failure status of `iscsiuio.service` when masked, because it causes CI instability.
=> Disable iscsiuio.service

dctest/init_test.go
Since yesterday, systemd-networkd-wait-online.service fails due to timeout during neco-apps bootstrap. (The reason is still unknown)
The failure itself doesn't seem a problem because the test code can already connect to boot servers.
Because neco-apps has a alert rule that checks all systemd services are OK, I decide to reset the failed status instead of ignoring the failed status during the test.
note: it may or may not be a temporary resolution.
=> reset failed status of systemd-networkd-wait-online.service

cilium/pre/kustomization.yaml, cilium/prod/kustomization.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
`ttlSecondsAfterFinished` causes the job to be deleted in 30 minutes; CKE will recreate the job.
=> Remove ttlSecondsAfterFinished from hubble-generate-certs Job

installer/Makefile
"apt-get install --print-uris --reinstall" does not show the filename
of the deb archive if the archive is already cached.
"apt-get download --print-uris" always shows the filename.
=> Use "apt-get download" to show deb filename

dctest/machines_test.go, docs/neco.md, pkg/neco/cmd/bmc_config_get.go, pkg/neco/cmd/bmc_config_get_repairpassword.go, pkg/neco/cmd/bmc_config_get_repairuser.go, pkg/neco/cmd/bmc_config_set.go, pkg/neco/cmd/bmc_config_set_repairpassword.go, pkg/neco/cmd/bmc_config_set_repairuser.go, pkg/neco/cmd/bmc_repair.go, pkg/neco/cmd/bmc_repair_dell.go, pkg/neco/cmd/bmc_repair_dell_discharge.go, pkg/neco/cmd/bmc_repair_dell_resetidrac.go, storage/bmc.go, storage/keys.go
This PR adds `neco bmc repair` subcommand and its descendants.
This PR also adds configurations of the user and password for those subcommands.
Please see the diff of `docs/neco.md` first.
=> Add "neco bmc repair" subcommand

artifacts.go, artifacts_ignore.yaml
- Downgrade the OS image to `3602.2.0` to investigate network failure.
- Ignore the Squid `6.5.0.1` image to prevent failure when prod release.
- Cilium `1.13.7.2` will be included in the next prod release.
=> Downgrade OS image to 3602.2.0

dctest/menu-ss.yml
The issue of not being able to increase cpu resources is under investigation.
Memory only seems to be OK, so I increased it.
=> Expand cs memory for dctest

progs/sabakan/upload.go
The container image files include their image names. i.e. they include registry name (like "ghcr.io") and username (like "cybozu").
On the other hand, the container image asset names does not include them.
As the result, Neco boot servers and worker nodes may get unexpected image files: an worker node want to get a image from a certain container registry (e.g. `ghcr.io/cybozu/xxx:n.n.n`) but it actually get a image from another container registry (e.g. `quay.io/cybozu/xxx:n.n.n`).
=> container image asset names should include container registry name

installer/setup/packages.go
The latest ubuntu cloud image does not include the `fwupd` and `popularity-contest` packages, so trying to purge these packages will result in an error.
Since `fwupd` and `popularity-contest` are still included in the iso image, I changed it to purge those packages in non-vm environments.
=> Remove fwupd and popularity-contest from the list to purge

cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
Kubernetes 1.27 changes high-cardinality label names for job pods.
=> Add ignore rules to security labels

.circleci/config.yml
This reverts commit 34a6e3d7ec6a1283222bdfe27d1faa0a6f6118da.
=> Revert "Relax CI workflow to allow release without upgrade test"

installer/Makefile
Since CI uses the latest version of ubuntu-cloud image, there is a possibility that the version of ubuntu-cloud image will be upgraded and CI will break by itself.
To prevent CI from breaking on its own, fix the version of the ubuntu cloud image to be used.
=> Fix ubuntu cloud image version

installer/setup/packages.go
The https://github.com/cybozu-go/neco/pull/2474  PR said that I needed to remove popularity-contest and fwupd, but in fact I only needed to remove popularity-contest.
Add fwupd again to the list to purge.
=> Add fwupd to the list to purge

Makefile.common, debian/usr/sbin/check-machine-state, debian/usr/sbin/retire-machine, etc/cke-template.yml, go.mod, go.sum, progs/cke/conf.go
This PR updates CKE to 1.27.4.
This PR also updates the cluster yaml for the repair queue,
which is introduced in CKE 1.27.4.
=> Update CKE to 1.27.4 to introduce repair queue

dctest/menu.yml, ignitions/common/files/opt/sbin/setup-var
When migrating the image registry for rook from quay.io to ghcr.io, it is necessary to save both the old and the new image on the volume.
related to: https://github.com/cybozu-private/neco-apps/pull/4499, https://github.com/cybozu-private/csa-apps/issues/2487
=> Expand k8s-containerd lvm for qemu

Makefile, Makefile.tools, bin/necoip
This PR adds `necoip` command, that helps us to find where the IP address comes from.
It will be installed on boot servers and Teleport nodes.
=> Add necoip command

bin/necoip
This PR adds `necoip` command the capability to search from sabakan machine entries.
=> Improve necoip command for admins

ignitions/common/systemd/node-exporter.service
This pr enables node_exporter's network_route collector.
Please see below for details.
- https://github.com/prometheus/node_exporter/pull/1811
- https://grafana.com/docs/agent/latest/static/configuration/integrations/node-exporter-config/
=> Enable node_exporter network_route collector

Makefile, Makefile.tools, bin/clusterdump, bin/nsdump
This PR adds the following commands:
- `nsdump <NAMESPACE>`: show all the namespace-scoped resource names in JSON
- `clusterdump`: show all the cluster-scoped resource names in JSON
=> Add nsdump and clusterdump commands

ignitions/common/files/etc/k8s-containerd/config.toml
Change the containerd configuration so that a timeout does not occur when pulling an image.
Set `image_pull_progress_timeout` to `0s` to prevent timeouts.
>A zero value means there is no timeout.
https://github.com/containerd/containerd/blob/v1.7.13/pkg/cri/config/config.go#L374
=> Disable the image pull progress timeout

worker/deb.go, worker/etcdpasswd.go, worker/operator.go
This PR added the parameter(named `envValues`) for `InstallDebianPackage()` and `installDebianPackage()` to set environment values.
Given values in `envValues` will be extracted like following and will be executed.
When `envValues` is given as `map[string]string{"HOME": "/home/cybozu"}`,  these values are extracted like following.
```console
systemd-run -p Environment=HOME=/home/cybozu ...
```
ref: https://github.com/cybozu-go/neco/pull/2506/files#diff-38861c4365e417f67e3b1020fb2297e10cd135406e2913894c4ed32c7f5d2aa4R116
=> Add InstallDebianPackage and installDebianPackage's parameter to give Env values for systemd-run

cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
This PR changes cilium-config to use white label list instead of black one for identities.
Arrowed label prefixes are below (except for default ones):
```
- k8s:app
- k8s:io.cilium.k8s.namespace.labels.team
- k8s:io.kubernetes.pod.namespace
- k8s:k8s-app 
- io.cilium.k8s.policy
- cybozu.io/family
- app.cybozu.io
- neco.cybozu.io/registry
- identity.neco.cybozu.io
```
=> Change to white identity list

cilium/pre/bgp_config.yaml, dctest/contents_test.go, dctest/run_test.go, etc/cilium-pre.yaml, pkg/neco/cmd/config_get.go, pkg/neco/cmd/config_set.go, progs/cke/resource.go, storage/config.go, storage/keys.go
This PR adds a new LB address block named `internet-cn`.
It renders the ConfigMap for MetalLB on dctest:
- without `neco config set lb-address-block-internet-cn`:
```
peers:
- peer-address: 127.0.0.1
peer-asn: 64699
my-asn: 64698
node-selectors:
- match-labels:
cke.cybozu.com/role: cs
address-pools:
- name: default
protocol: bgp
addresses:
- 10.72.32.0/20
- name: bastion
protocol: bgp
addresses:
- 10.72.48.48/28
auto-assign: false
- name: internet
protocol: bgp
addresses:
- 172.19.0.16/28
auto-assign: false
```
- with `neco config set lb-address-block-internet-cn`:
```
peers:
- peer-address: 127.0.0.1
peer-asn: 64699
my-asn: 64698
node-selectors:
- match-labels:
cke.cybozu.com/role: cs
address-pools:
- name: default
protocol: bgp
addresses:
- 10.72.32.0/20
- name: bastion
protocol: bgp …
```
=> Add optional internet-cn LoadBalancer config

etc/cke-template.yml
* In the case of `unhealthy`, the iDRAC of the unhealthy machine may not
be working.  So we should skip `neco bmc repair dell reset-idrac`.
* In the case of `unreachable`, SSH to the machine is likely to fail.
So we should skip `ckecli ssh $1 ...`.
* A repair command in the form of `sh -c '...'` is hard to cancel.
We should use `sh -c 'exec ...'` if possible.
=> Fix repair queue config to use appropriate commands

etc/cke-template.yml
In some environments (CI and stage1), the number of pods per node is insufficient.
ref. https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration
=> Increase maxPods in kubelet to 150

artifacts.go, artifacts_ignore.yaml, ignitions/common/systemd/docker.service
This PR updates Flatcar Linux to 3815.2.0.
The `torcx` has been removed from Flatcar Linux 3760.
So this PR removes the torcx-related settings from the `docker.service`.
https://www.flatcar.org/docs/latest/provisioning/torcx/
=> Flatcar Linux 3815.2.0

image.go
In the current implementation, when pulling container images from neco, the credentials managed by either docker or neco are used.
When pulling container images, docker credentials will be used.
https://github.com/cybozu-go/neco/blob/b13aacd3b261ac6ba648a3d2e19a46839d928f6d/docker.go#L44-L47
When pulling a container image to tarball it, the credentials stored in neco will be used.
https://github.com/cybozu-go/neco/blob/b13aacd3b261ac6ba648a3d2e19a46839d928f6d/image.go#L42
I would like to be able to manage credentials in one of the two, because if I manage credentials in both, there is a possibility that credential update omissions may occur.
This PR will change to use docker credentials when pulling container images to tarball them.
I plan to remove the functions that manage credentials …
=> Use docker credentials when pulling container images

pkg/generate-sabakan-machines/cmd/root.go
`generate-sabakan-machines` fails when the date of `supportDateString` is one digit.
```
$ cat <<EOF > input.csv
環境,論理ラック番号,物理ラック番号,シリアル番号,機種,role,サポート開始日
env,1,mydc rack1,serial,model,boot,2024/5/9
EOF
$ go install ./pkg/generate-sabakan-machines
$ generate-sabakan-machines --machine-type-boot=r6525-boot-1 --machine-type-cs=r6525-cs-1 --machine-type-ss=r7525-ss-1 input.csv
Error: parsing time "2024/5/9" as "2006/1/02": cannot parse "9" as "02"
```
=> Fix time parse format

dctest/suites_test.go
This PR removes the time display of dctest test.
Now Ginkgo displays the execution time of `By`. So start time and end time of each test is unnecessary.
(The time was not displayed at Ginkgo v1.)
```
Neco setup should complete updates
/home/actions/go/src/github.com/cybozu-go/neco/dctest/setup_test.go:137
START: 2024-06-05T00:09:17Z                                        // Remove
STEP: Waiting for request to complete @ 06/05/24 00:09:17.51     // Ginkgo displays the execution time of "By".
STEP: Installing sshd_config and sudoers @ 06/05/24 00:09:43.499
END: 2024-06-05T00:09:43Z                                          // Remove
• [26.030 seconds]
```
=> Remove time display

etc/cke-template.yml
Revert commit 8f311b4ef48c5cb2b44b09382c3e9101698116fd due to the massive volume of metrics.
=> Revert "Audit creation of cilium.io resources"

cilium/pre/kustomization.yaml, cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/kustomization.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, dctest/upgrade_test.go, etc/cilium-pre.yaml, etc/cilium.yaml
This PR:
- changes `updateStrategy` of cilium-agent to `OnDelete`
- increases `bpf-map-dynamic-size-ratio` from `0.0025` to `0.005`
Signed-off-by: Tomoki Sugiura <tomoki-sugiura@cybozu.co.jp>
=> Update Cilium bpf-map-dynamic-size-ratio to 0.005

Makefile.common, ignitions/common/files/etc/k8s-containerd/config.toml, ignitions/common/files/opt/bin/load-containerd-image
- Update containerd to 1.7.20.
- Enable image pull with sync fs in k8s-containerd config to prevent data inconsistencies in the event of an unexpected shutdown.
- Fix load-containerd-image script.
=> Update containerd version and modify the configuration

cilium/pre/kustomization.yaml, cilium/prod/kustomization.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
This PR adds cilium's api-rate-limit config.
note: Cilium doesn't support api-rate-limit helm value at 1.13 (it's supported from 1.15).
=> Add cilium api-rate-limit config

pkg/neco/cmd/apply-firmware.go, pkg/neco/cmd/isoreboot.go
part of https://github.com/cybozu-private/neco-tasks/issues/397
This PR set the default timeaout and timeout option to `neco isoreboot` and `neco apply-firmware`.
Sometimes SSH to the worker machines hangs and the command stops.
To prevent this, I set a timeout to child command execution.
According to the execution log of past runs, execution time of `isoreboot`'s child command was about 12~13 seconds; `apply-firmware`'s child command was about 70 seconds, on worker nodes.
So I set the default timeout as follows:
- isoreboot: 30sec
- apply-firmware: 5min
=> Set timeout to FW update commands

dctest/Makefile, dctest/machines_test.go, dctest/run_test.go, systemd.go
This PR fixes three flaky behaviors to improve CI stability.
- test: retry neco bmc config set bmc-user
Previously, `neco bmc config set bmc-user` sometimes fails because it fails to send packets and receives a message with `"missing HTTP content-type"`.
This PR implements `execRetryAt` and `handleBMCRetry` to see if it is caused by connection error.
- neco-worker: wait changing systemd service state until transient state ends
neco-worker was not deterministic at stopping systemd service, because `systemd` rejects `systemd stop <service_name>` with message `"Job for <service_name> canceled."` when it is already changing its state, especially when it is in `activating` or `deactivating` state.
- test: wait placemat
In minor cases PID of `placemat2` is not observed and CI fails. This fix …
=> Fix CI instability

bin/clusterdump, bin/necoip, bin/nsdump
This PR supports `-h` and `--help` options for `nsdump`, `clusterdump`, and `necoip`.
=> add help to nsdump, clusterdump, and necoip commands

dctest/machines_test.go
This PR retries `neco bmc config set` operations when error message indicates a network error, because they are idempotent.
=> test: retry idempotent neco bmc config set

Makefile.common, artifacts_ignore.yaml
Ref. https://github.com/cybozu-private/neco-apps/pull/5287
=> Bump Argo CD version to 2.11.7 from 2.10.2

.circleci/config.yml
Fix the dctest-functions-release,  dctest-upgrade-release  to not use `artifacts_release.go`.
=> Fix an issue with release tests referencing unused file

pkg/neco-rebooter/controller.go, pkg/neco-rebooter/controller_test.go, pkg/neco-rebooter/metrics.go, pkg/neco-rebooter/metrics_test.go, pkg/neco-rebooter/utils.go
fix neco-rebooter to 
- manage orphaned cke reboot queue entry
- hide processing group metrics when number of the reboot list entry is 0
=> fix neco-rebooter

dctest/join_remove_test.go, dctest/run_test.go, dctest/setup_test.go
This PR fixes the flaky test in `setup_test.go`.
Stopping Vault in neco update process sometimes fails as follows.
I think neco recover will solve the problem, so when aborted, it will call neco recover.
```
Neco setup should complete updates
/tmp/release/dctest/setup_test.go:138
STEP: Waiting for request to complete @ 09/04/24 15:25:12.455
[FAILED] in [It] - /tmp/release/dctest/setup_test.go:140 @ 09/04/24 15:35:14.457
• [FAILED] [602.002 seconds]
Neco setup [It] should complete updates
/tmp/release/dctest/setup_test.go:138
[FAILED] Timed out after 600.001s.
Expected success, but got an error:
<*errors.errorString | 0xc000174070>: 
request is not completed: Boot servers: [0 1 2]
Update process
status: aborted
version: 2024.08.28-31066
members: [0 1 2]
started: 2024-09-04T15:25:09Z
Boot …
```
=> dctest: try to recover when update request is aborted

dctest/run_test.go
This PR fixed wrong use of `StopTrying()`.
In this case, we may need to call `StopTrying().Now()`.
https://pkg.go.dev/github.com/onsi/gomega#pkg-variables
=> dctest: Fixed wrong use of StopTrying

dctest/join_remove_test.go, dctest/run_test.go, dctest/setup_test.go
https://github.com/cybozu-go/neco/pull/2670 was ineffective. I will try to correct it.
When limiting the number of recoveries, The `Eventually` may terminate before the rerun completes. (as follows)
So I try to repeat `neco recover` forever.
https://github.com/cybozu-private/neco-apps/actions/runs/10822616854/job/30031096472
```
Neco setup should complete updates
/home/actions/go/src/github.com/cybozu-go/neco/dctest/setup_test.go:138
STEP: Waiting for request to complete @ 09/12/24 04:44:43.666
Boot servers: [0 1 2]
Update process
status: aborted
version: 9999.12.31-99999
members: [0 1 2]
started: 2024-09-12T04:44:41Z
Boot server 0
step: 4
condition: aborted
message: other boot server failed to update: 2
Boot server 1
step: 3
condition: running
Boot server 2
step: 3
condition: aborted …
```
=> dctest: try to recover forever

cilium/pre/kustomization.yaml, etc/cilium-pre.yaml
This PR updates Cilium's endpoint-create API rate limit in stages.
Details are below.
- Remove `mean-over` because it is the same as the default value.
- https://github.com/cilium/cilium/blob/24d61daa20b1e1e1074ad73e4a9b6fea5374b95b/pkg/rate/api_limiter.go#L27
- Change `max-parallel-requests` to 16
- Remove `min-parallel-requests`(default 0).
- Change `estimated-processing-duration` to 5s
- This means Cilium will raise `rate-limit` unless Pod creation time exceeds this value.
- Enables log
- `rate` subsystem will output logs
Default values of endpoint-create API rate limit are here:
https://github.com/cilium/cilium/blob/c1044d67cab67eca42517a5f385ccb06b4d49219/daemon/cmd/api_limits.go#L23-L32
=> Update Cilium endpoint-create API rate limit in stages

artifacts.go, artifacts_ignore.yaml, ignitions/common/files/etc/fstab
This PR updates Flatcar OS to 3975.2.1 and adds dependencies to `/etc/fstab`.
With Flatcar OS 3975.2.1, the order of `setup-var.service` and volume mounting is often reversed, and the CI(neco's bootstrap) became too unstable. (It almost always fails.)
To prevent this, I set `x-systemd.requires` to `/etc/fstab` and stabilize the order.
=> Flatcar OS 3975.2.1

debian/usr/bin/trigger-reboot-all-nodes
This PR allows users to turn off the daily reboot.
If users create `/tmp/no-reboot` on all boot servers, the daily reboot will be disabled.
=> Allow disabling daily reboot

ignitions/common/files/opt/sbin/neco-wait-dhcp-online, ignitions/common/files/opt/sbin/setup-local-network, ignitions/common/networkd/01-eth0.network, ignitions/common/networkd/01-eth1.network
From [Flatcar Linux 3975](https://www.flatcar.org/releases#release-3975.2.0),  the port numbers are added to the network device names of our actual machines.
To accommodate this change, update the initialization scripts.
=> Add new network I/F settings

pkg/generate-sabakan-machines/cmd/root.go
- add "ss2" sabakan role in `generate-sabakan-machines`
- remove shorthand strings because it's difficult to assign one character to "ss2"
=> add "ss2" sabakan role

cilium/prod/kustomization.yaml, etc/cilium.yaml
This is a follow-up PR for https://github.com/cybozu-go/neco/pull/2682 .
This PR updates Cilium endpoint-create API's rate-limit config in prod.
=> Update cilium endpoint-create API rate-limit config in prod

cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
"endpoint-manager" which is a subsystem in cilium-agents has GC system.
This GC sometimes removes healthy CEP.
(I think this is due to poor coordination with Coil, but the root cause is not currently known.)
It was implemented as a way to deal with the bug with dockershim.
However, dockershim is not used in Neco and as far as I looked up I cannot find the CEP that has to be garbage collected.
This PR disables endpoint-manager's GC and avoid deleting healthy CEP.
=> Disable endpoint-manager's gc in cilium-agent

ignitions/roles/cs/systemd/cpu-governor.service
If we set SysProfile to `PerfOptimized`, there are no files in `/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`.
In such situation, we want to skip cpu-governor.service.
=> Fix cpu-governor.service to set performance governor for existing CPU

artifacts_ignore.yaml, worker/deb.go, worker/etcdpasswd.go, worker/operator.go
- Set bearer token in header.
- Change download url from `browser_download_url` to `url`. Because `browser_download_url` cannot be used with token.
ref. https://github.com/cybozu-private/neco-tasks/issues/529
=> Use token to download a debian package

progs/etcd/templates.go
part of https://github.com/cybozu-private/neco-tasks/issues/456
after checking this feature is working in neco, I'll enable this in CKE too.
PR 
- https://github.com/cybozu-go/cke/pull/787
=> Enabling etcd data corruption detection

dctest/upgrade_test.go
This PR prints additional information when CKE fails to complete (especially in case of updating Cilium).
=> test: show additional information when CKE fails to complete

Makefile, constants.go, dctest/boot-ip-setter_test.go, dctest/join_remove_test.go, dctest/suites_test.go, debian/DEBIAN/postinst, debian/DEBIAN/prerm, debian/lib/systemd/system/boot-ip-setter.service, docs/boot-ip-setter.md, go.mod, menu/cluster_yaml_generator.go, menu/testdata/cluster.yml, pkg/boot-ip-setter/ip.go, pkg/boot-ip-setter/ip_test.go, pkg/boot-ip-setter/main.go, pkg/boot-ip-setter/metrics.go, pkg/boot-ip-setter/metrics_test.go, pkg/boot-ip-setter/mock_test.go, pkg/boot-ip-setter/netif.go, pkg/boot-ip-setter/netif_test.go, pkg/boot-ip-setter/suites_test.go
This PR implementes https://github.com/cybozu-go/neco/issues/2357 .
Add a new daemon `boot-ip-setter` on boot servers, and it sets virtual IPs.
=> Add boot-ip-setter

Makefile.common, Makefile.tools
- `JSONNET_VERSION` remains 0.20.0, no change required.
https://github.com/argoproj/argo-cd/blob/dc43124058130db9a747d141d86d7c2f4aac7bf9/go.mod#L47
- kustomize 5.4.3 for windows binary has `.exe` extension.
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.4.3
=> Bump Argo CD version from 2.11.7 to 2.13.2 and its dependencies

cilium/dctest/upstream.yaml, cilium/dctest/values.yaml, cilium/pre/upstream.yaml, cilium/pre/values.yaml, cilium/prod/upstream.yaml, cilium/prod/values.yaml, etc/cilium-dctest.yaml, etc/cilium-pre.yaml, etc/cilium.yaml
This reverts commit 96d2b10f27ad425845b7eb1df3fdb9a5c0b80986, reversing changes made to 8670e0e13d86e6c33d3d472c9a79c2947f1a056b.
=> Revert "Merge pull request #2785 from cybozu-go/cilium-operator-recrete"

.circleci/config.yml, dctest/upgrade_test.go
CircleCI terminates test programs when they run without output longer than a certain limit (default: 10m).
On the other hand, some Ginkgo jobs should wait for some time to see completion of slow work.
Therefore, we need to tell CircleCI to avoid terminating jobs longer than the period set to Ginkgo jobs.
This PR clarifies the division of responsibility:
- Ginkgo jobs can use round number
- CircleCI should wait for an extra time (set to 2m)
=> Fix no-output termination

etc/sabakan-state-setter.yml
See-also: https://github.com/cybozu-private/neco-tasks/issues/473
=> sabakan-state-setter: Add config for monitoring Prometheus alerts

.circleci/config.yml
This PR splits the test for artifact.go from main and makes it not required.
=> Split the test for artifact.go from main to check-artifacts
