cybozu-go/neco

pkg/neco/cmd/leave.go
pkg/neco/cmd/recover.go
storage/keys.go
storage/storage.go
storage/storage_test.go

Add some sub commands of neco
- `neco leave`
- `neco recover`
https://github.com/cybozu-go/neco/blob/master/docs/neco.md#synopsis

Add neco leave|recover command

---

progs/vault/policies.go

Vault 1.0.0 changed recommended admin policy format.

[vault] fix policy for admin

---

dctest/Makefile
dctest/test-light.sh

Add a new target "stop" to stop placemat.service.

[dctest] Update placemat target to launch placemat by systemd-run

---

artifacts.go
artifacts_new.go
debian/DEBIAN/postinst
docs/neco.md
etc/coil-deploy.yml
pkg/neco/cmd/completion.go
pkg/neco/cmd/ipmipower.go

What included in this PR are:
* `neco completion` subcommand for bash completion.
* `neco ipmipower` subcommand to control machine power.
* Update `coil-deploy.yml` as in coil 1.0.0 (ref https://github.com/cybozu-go/coil/commit/8e6693e3ce13e7206a7dc2171bcf7034e50cf265#diff-b7d390bc2807a4cd1ddda3e8653bab05).

Miscellaneous enhancements

---

storage/config.go

Reduce github check interval from 10 to 1 min.

---

pkg/git-neco/cmd/draft.go
pkg/git-neco/cmd/github.go
pkg/git-neco/cmd/review.go

if there is a draft PR for the current branch.

[git-neco] "git neco review" marks draft ready for review

---

updater/github.go

neco-updater should survive on GitHub errors including rate limit
violation.

[updater] do not fail on GitHub API error

---

.circleci/config.yml
gcp/compute.go
pkg/necogcp/cmd/necotest_createimage.go

Also, fix a critical bug that vmx-enabled image for neco-test
project is not downloaded assets such as ubuntu custom image.

Add weekly workflow to build vmx-enabled image

---

Makefile.tools
gcp/artifacts.go
gcp/types.go
gcp/vmxenabled.go
go.mod
vendor/github.com/cybozu-go/placemat/CHANGELOG.md
vendor/github.com/cybozu-go/placemat/node_vm.go
vendor/github.com/cybozu-go/placemat/server.go
vendor/github.com/cybozu-go/sabakan/v2/CHANGELOG.md
vendor/github.com/cybozu-go/sabakan/v2/README.md
vendor/github.com/cybozu-go/sabakan/v2/version.go
vendor/modules.txt

- ct: It is used transpiling from cloud-init to ignition on the
coil/CKE.
- libseccomp-dev: It is required by building containerd.
- bionic PPA: It solve file conflict problem of containers-common.
- containerd: Install by go install using own vendor

[necogcp] Install files to vmx-enabled

---

.circleci/config.yml
Makefile
Makefile.tools
gcp/artifacts.go
gcp/types.go
gcp/vmxenabled.go

[necogcp] Install protobuf from source

---

.circleci/config.yml
gcp/artifacts.go

Also update gcp/artifacts.go to solve podman build.

Update Go to 1.12.1 for CircleCI and container images

---

ignitions/common/common.yml
ignitions/common/files/opt/sbin/fetch-chrony-image
ignitions/common/systemd/chronyd.service

retry fetching chrony container image

fix failure on bootstrap worker node

---

artifacts.go
dctest/upgrade.go

Waiting for https://github.com/cybozu/neco-containers/pull/175 to be merged.

[dctest] update for cke-1.13.17

---

pkg/sabakan-state-setter/main.go
pkg/sabakan-state-setter/metrics.go
pkg/sabakan-state-setter/metrics_test.go

This pull request made the following changes
- fix the bug about using the same metrics repeatedly from Prometheus response 
- mock Prometheus response and add one unit test

Mock test for sabakan-state-setter

---

artifacts.go

Update cke version from 1.14.0 to 1.14.1 in artifacts.go

Upgrade cke version

---

dctest/machines.go
pkg/neco/cmd/bmc_setuphw.go

To reduce the time for dctest-functions

Wait for setup-hw container is running

---

gcp/artifacts.go

gcp: update Go and CoreOS

---

pkg/sabakan-state-setter/controller.go
pkg/sabakan-state-setter/machine_state_source.go
pkg/sabakan-state-setter/strategy.go

[sabakan-state-setter] Add ipv4 field to the log format

[sabakan-state-setter] Output logs when machines' state changed

---

dctest/suites.go
go.mod
pkg/generate-sabakan-machines/main.go
vendor/github.com/cybozu-go/cke/CHANGELOG.md
vendor/github.com/cybozu-go/cke/RELEASE.md
vendor/github.com/cybozu-go/cke/infrastructure.go
vendor/github.com/cybozu-go/cke/kubeconfig.go
vendor/github.com/cybozu-go/cke/pki.go
vendor/github.com/cybozu-go/cke/vault.go
vendor/github.com/cybozu-go/cke/version.go
vendor/modules.txt

also update go.mod with latest cke

[generate-sabakan-machines] Fix rack format to integer

---

artifacts.go
pkg/sabakan-state-setter/sabakan.go

sabakan-state-setter: add "application/json" content-type header

---

dctest/sabakan_state_setter.go
go.mod
ignitions/common/common.yml
ignitions/common/files/etc/systemd/system/rngd.service.d/non_vm.conf
ignitions/common/systemd/sabakan-cryptsetup.service
ignitions/common/systemd/setup-var.service
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/modules.txt

Add rngd.service to `Wants` and `After` settings of setup-var.service.

[ignitions] Enable rngd.service to increase entropy for /dev/urandom

---

artifacts.go
etc/sabakan-state-setter.yml

https://github.com/cybozu-go/neco/issues/487

Update sabakan-state-setter config

---

Makefile.tools

Server side will be updated by https://github.com/cybozu-go/neco-apps/pull/107

Update argocd CLI to 1.2.0-rc2

---

etc/cke-template.yml
etc/coil-deploy.yml

Please merge this PR after https://github.com/cybozu-go/neco-apps/pull/118 has been merged.

Remove boot-taint

---

progs/sabakan/upload.go

Add and use assetsUploadWithRetry on neco.

---

Makefile
dctest/Makefile
dctest/passwd.yml
go.mod

- Replace ignition's passwd.yml if the environment is dctest
- Add `root` user to the passwd.yml for dctest
- The password of `root` is "root"

Set password for root user

---

README.md

Add steps to run the virtual data center.

[ci skip] update README.md

---

Makefile.tools
artifacts.go
etc/cke-template.yml

- Update components in `Makefile.tools`
- Enable EvenPodsSpread feature gate
- add the option(`--feature-gates="EvenPodsSpread=true"`) to both extra_args fields of kube-apiserver and kube-scheduler in cke-template.yaml
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
- Update artifacts (CKE & Coil)

Update components for k8s 1.16

---

etc/squid.yml
etc/unbound.yml

https://github.com/cybozu-go/neco/issues/661

Sleep in preStop hook for graceful termination

---

.circleci/config.yml
dctest/ignitions.go
dctest/suites.go
docs/ignition.md
docs/placemat-menu.md
ignitions/roles/ss/files/etc/udev/crypt-base-path
ignitions/roles/ss/files/etc/udev/rules.d/99-neco.rules
ignitions/roles/ss/files/opt/sbin/setup-partition
ignitions/roles/ss/site.yml
ignitions/roles/ss/systemd/setup-partition.service

Fix ignition files and a udev rule for SS nodes.
This PR gives the following change:
- Create a partition in each encrypted HDD on SS nodes.
- Create symlinks to the partitions into `/dev/crypt-part/by-path/`.
- Some refactor of CircleCI Jobs.

add setup-partition service

---

.circleci/config.yml
artifacts.go
dctest/unbound.go
ignitions/common/common.yml
ignitions/common/systemd/iptables-notrack-udp-53.service
pkg/download-binaries/main.go

- Add `iptables-notarack-udp-53.service` to stop tracking UDP packets for DNS
- Fix download-binaries
- Combine to one zip file
- Fix CI

ignitions: stop tracking UDP packet for DNS

---

ignitions/roles/ss/files/opt/sbin/setup-partition

setup-partition: enable udev_sync

---

Makefile
pkg/necogcp-app/main.go
pkg/sabakan-state-setter/controller.go
worker/operator.go

add nilerr and custom-checker test

---

artifacts.go

Signed-off-by: dulltz <isrgnoe@gmail.com>

Teleport 4.2.4, CoreOS 2345.3.0

---

dctest/reboot.go

Retry `neco ipmipower {start,stop}`.
ref: https://github.com/cybozu-go/neco-apps/pull/430

retry neco ipmipower

---

dctest/reboot.go
dctest/sabakan_state_setter.go

Add debug log for sabakan-state-setter and reboot test

---

etc/pod-security-policy.yml

https://github.com/cybozu-go/neco/issues/844

Add allow-csi-volume policy to psp

---

artifacts.go
gcp/artifacts.go
go.mod
vendor/github.com/coreos/etcd/clientv3/balancer/resolver/endpoint/endpoint.go
vendor/github.com/coreos/etcd/clientv3/client.go
vendor/github.com/coreos/etcd/clientv3/credentials/credentials.go
vendor/github.com/coreos/etcd/clientv3/ctx.go
vendor/github.com/coreos/etcd/clientv3/retry_interceptor.go
vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes/md.go
vendor/github.com/coreos/etcd/version/version.go
vendor/modules.txt

Signed-off-by: dulltz <isrgnoe@gmail.com>

etcd: 3.3.19.1

---

dctest/contents.go
dctest/menu.yml
dctest/suites.go

dctest: increase SS for Rook/Ceph dctest.

---

dctest/machines.go

dctest: retry "neco bmc setup-hw".

---

bin/run-dctest.sh
dctest/Makefile
dctest/menu-ss.yml

Add menu-ss for Rook test

---

artifacts.go

Update Vault to 1.3.4.1.

---

etc/cke-template.yml

Add kubelet extra args for cAdvisor

---

artifacts.go
artifacts_ignore.yaml

update etcd to v3.3.22

---

artifacts.go
etc/cke-template.yml
go.mod
vendor/github.com/cybozu-go/cke/CHANGELOG.md
vendor/github.com/cybozu-go/cke/Makefile
vendor/github.com/cybozu-go/cke/README.md
vendor/github.com/cybozu-go/cke/cluster.go
vendor/github.com/cybozu-go/cke/go.mod
vendor/github.com/cybozu-go/cke/images.go
vendor/github.com/cybozu-go/cke/op/k8s/config.go
vendor/github.com/cybozu-go/cke/op/k8s/kubelet_boot.go
vendor/github.com/cybozu-go/cke/op/k8s/kubelet_restart.go
vendor/github.com/cybozu-go/cke/op/k8s/scheduler_boot.go
vendor/github.com/cybozu-go/cke/op/status.go
vendor/github.com/cybozu-go/cke/phase.go
vendor/github.com/cybozu-go/cke/sabakan/generator.go
vendor/github.com/cybozu-go/cke/sabakan/integrate.go
vendor/github.com/cybozu-go/cke/sabakan/op.go
vendor/github.com/cybozu-go/cke/sabakan/score.go
vendor/github.com/cybozu-go/cke/server/node_filter.go
vendor/github.com/cybozu-go/cke/server/strategy.go
vendor/github.com/cybozu-go/cke/status.go
vendor/github.com/cybozu-go/cke/vault.go
vendor/github.com/cybozu-go/cke/version.go
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
vendor/k8s.io/apimachinery/pkg/util/json/json.go
vendor/modules.txt

- Update CKE to v1.17.6
- Add `.options.kube-scheduler.priorities` to cke-template.yml.
- Remove `.pod_subnet` from cke-template.yml.

Add config for scheduling policy to increase EvenPodsSpreadPriority weight

---

Makefile.tools
artifacts.go
artifacts_ignore.yaml

Signed-off-by: dulltz <isrgnoe@gmail.com>

Update kustomize to v3.6.1 for ArgoCD 1.5.6

---

artifacts.go
artifacts_ignore.yaml

Update cke to v1.17.9

---

ignitions/common/common.yml
ignitions/common/systemd/udev-trigger.service
ignitions/common/systemd/udev-trigger.timer

ignition: exec udevadm trigger periodically

---

dctest/reboot.go
dctest/sabakan_state_setter.go

Remove debug code added by #849

Delete debug code

---

gcp/app/server.go
gcp/config.go

Make GAE app delete test instances both from asia-northeast1-c and asia-northeast2-c

---

docs/gcp/neco-test.md
pkg/necogcp-app/app.yaml

GAE to use Go 1.13 and update documentation

---

pkg/ingress-watcher/cmd/export.go
pkg/ingress-watcher/cmd/push.go

Fix private http.Transport

---

pkg/ingress-watcher/metrics/metrics.go
pkg/ingress-watcher/watch/watch.go
pkg/ingress-watcher/watch/watch_test.go

In order to write robust alert rules, expose watchInterval.

ingress-watcher: expose watch-interval

---

docs/gcp/config.md
gcp/app/server.go
gcp/compute.go
gcp/config.go

Make GAE app extend test instances to night

---

pkg/ingress-watcher/cmd/root.go

ingress-watcher: register watch-interval metrics to registry

---

docs/gcp/config.md
docs/gcp/instance-labels.md
docs/gcp/neco-test.md
docs/gcp/necogcp.md
gcp/app/server.go
gcp/compute.go
gcp/config.go
pkg/necogcp/cmd/necotest_extend.go

Fix to keep CI instances at least two hours

---

docs/ingress-watcher.md
go.mod
pkg/ingress-watcher/cmd/export.go
pkg/ingress-watcher/cmd/push.go
pkg/ingress-watcher/metrics/metrics.go
pkg/ingress-watcher/watch/watch.go
pkg/ingress-watcher/watch/watch_test.go
progs/ingresswatcher/conf.go
progs/ingresswatcher/templates.go

ingress-watcher: set instance, job, and code labels appropriately

---

README.md
gcp/artifacts.go
go.mod
vendor/github.com/cybozu-go/placemat/CHANGELOG.md
vendor/github.com/cybozu-go/placemat/Makefile
vendor/github.com/cybozu-go/placemat/cluster.go
vendor/github.com/cybozu-go/placemat/go.mod
vendor/github.com/cybozu-go/placemat/node.go
vendor/github.com/cybozu-go/placemat/node_volume.go
vendor/modules.txt

ci: update placemat to 1.5.0

---

dctest/cke.go
etc/cke-template.yml
gcp/artifacts.go
menu/cluster.go
menu/testdata/cluster.yml

ci: change some parameters to stabilize

---

Makefile.tools
artifacts.go

to get teleport binaries reliably.

Add --retry-connrefused flag to wget

---

.circleci/config.yml
.gitignore
Makefile
Makefile.common
Makefile.tools
dctest/Makefile

Use CircleCI cache for downloaded artifacts

---

debian/usr/sbin/kill-old-login-sessions

- send SIGKILL on `loginctl kill-session`
- ~kill orphaned bash processes (whose PPID is 1)~

send SIGKILL on loginctl kill-session

---

artifacts.go
dctest/menu-ss.yml
dctest/menu.yml

Extend cs server's memory to resolve dctest memory exhaustion.

extend cs memory

---

artifacts.go
artifacts_ignore.yaml
dctest/reboot.go
docs/placemat-menu.md
generator/generate.go
menu/cluster.go
menu/resource.go
menu/template.go
menu/testdata/cluster.yml
menu/yaml.go
menu/yaml_test.go
types.go

Migrate from CoreOS Container Linux to Flatcar.

---

.circleci/config.yml

disable upgrade ci job temporarily.

---

Makefile.tools
artifacts.go
artifacts_ignore.yaml
dctest/reboot.go
dctest/squid.go
dctest/unbound.go
dctest/upgrade.go
etc/cke-template.yml

- Use CKE 1.18.0 & Kubernetes 1.18.9
- Update related tools version

Upgrade Kubernetes to 1.18

---

artifacts.go
etc/coil.yaml

Update Coil to 2.0.2.

---

etc/squid.yml
etc/unbound.yml

fix sh arguments

---

artifacts.go
dctest/suites.go
dctest/upgrade.go
ignitions/common/files/opt/sbin/setup-iptables-rules

Remove unnecessary rules

---

ignitions/common/systemd/disable-transparent-hugepage.service

Enable transparent-hugepage on VM

---

docs/neco.md
pkg/neco/cmd/ipmipower.go
pkg/neco/cmd/reboot_and_wait.go

Implement "neco reboot-and-wait" that reboots a machine and waits for its start-up.

---

Makefile.common

Periodical container update

---

artifacts.go

Upgrade sabakan to v2.5.3

---

dctest/bootstrap/suite_test.go
dctest/suites.go

Print timestamps before and after each test

---

.gitignore
Makefile
Makefile.common
artifacts.go

ci: remove windows-related files from deb package

---

dctest/contents.go

Modify cke-template.yaml on all boot servers.

---

README.md
artifacts.go
go.mod
vendor/github.com/cybozu-go/placemat/CHANGELOG.md
vendor/github.com/cybozu-go/placemat/node.go
vendor/github.com/cybozu-go/placemat/node_volume.go
vendor/github.com/cybozu-go/placemat/runtime.go
vendor/modules.txt

- bump placemat to v1.5.3
- apply generate artifacts

bump placemat to v1.5.3

---

progs/vault/templates.go

vault: expose prometheus metrics

---

.circleci/config.yml
Makefile.common
Makefile.tools
artifacts.go

Update teleport to v5.0.0

---

Makefile.common
artifacts.go

Update containerd to 1.4.3

---

ignitions/common/files/opt/sbin/setup-iptables-rules

Purge NOTRACK config in ignition

---

Makefile.common
artifacts.go

Update Teleport to 5.0.1

---

pkg/ingress-watcher/watch/watch.go

Show status code of ingress-watcher

---

Makefile.common

upgrade teleport v5.0.2

---

artifacts.go

Update Flatcar Container Linux to 2605.10.0.

---

artifacts.go
dctest/menu-ss.yml

dctest: increase # of CPUs for storage servers.

---

etc/cke-template.yml

Configure https://github.com/cybozu-go/neco/issues/988 .

Set PodTopologySpread weight

---

etc/cke-template.yml

Revert "Set PodTopologySpread weight"

---

ignitions/common/files/etc/k8s-containerd/config.toml
ignitions/common/systemd/k8s-containerd.service

Add registry mirror configurations for containerd

---

docs/dctest.md

Signed-off-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>

add document for MENU_ARG option

---

etc/coil.yaml
etc/pod-security-policy.yml

use MayRunAs for fsgroup

---

etc/squid.yml
etc/unbound.yml

Fix squid and unboud preStop hook.

---

etc/cke-template.yml

Use KubeSchedulerConfig v1alpha2

---

etc/cke-template.yml

Revert "Use KubeSchedulerConfig v1alpha2"

---

artifacts.go
etc/cke-template.yml

This reverts commit f0a893081f049d97f7a4bfb85c5996b8443ad0be.

Revert "Revert "Use KubeSchedulerConfig v1alpha2""

---

artifacts.go
etc/coil.yaml

also this updates etcd container and Flatcar.

Update coil to 2.0.4

---

ignitions/common/files/etc/k8s-containerd/config.toml
ignitions/common/systemd/k8s-containerd.service

Using ClusterIP services to access registry mirrors

---

.circleci/config.yml
Makefile.tools
bin/run-dctest.sh
dctest/Makefile

Use cache for dctest CI.

---

.circleci/config.yml
bin/run-dctest.sh

ci: Fix cache use.

---

pkg/neco/cmd/bmc_setuphw.go

Suppress sleep in "neco bmc setup-hw" for VM.

---

ignitions/common/files/opt/sbin/setup-hw

The same as #1345 for worker hosts.

ignitions: reduce wait for setup-hw on VM

---

docs/placemat-menu.md

Update link that references Placemat

---

ignitions/common/files/etc/k8s-containerd/config.toml
ignitions/common/files/etc/systemd/resolved.conf
ignitions/common/systemd/k8s-containerd.service

Enable worker nodes to use domain names without local suffix.

---

etc/cke-template.yml

change ss node taints to run debug container on ss nodes

---

etc/pod-security-policy.yml

This caused regression in neco-apps CI.

Revert Squid PSP

---

artifacts.go

Update Sabakan to 2.5.6.

---

Makefile
coil/daemonset.yaml
coil/kustomization.yaml
etc/coil.yaml

coil: update DaemonSet Pods in bulk.

---

Makefile
Makefile.common
Makefile.tools

kubeseal is a CLI tool for Bitnami's Sealed Secrets.

Bundle kubeseal

---

dctest/menu-ss.yml

expand CPU to stabilize neco-apps CI

---

etc/cke-template.yml
ignitions/common/files/etc/fstab

rook: add /var/lib/rook to use block device

---

Makefile.common

Update moco to v0.7.0

---

Makefile.common

Update containerd to 1.4.4

---

ignitions/common/systemd/bird.service

Set log-driver option to bird container

---

menu/cluster_yaml_generator.go
menu/testdata/cluster.yml

Use raw format

---

dctest/join_remove_test.go
dctest/run_test.go
docs/neco.md
worker/etcd.go
worker/operator.go
worker/worker.go

Always restart etcd after an update request has completed.

---

.gitignore

Ignore op-work-mac

---

debian/lib/systemd/system/teleport-node.service

Add 'team=neco' label to Teleport nodes.

---

Makefile.common
Makefile.tools
constants.go
dctest/node-dns_test.go
debian/DEBIAN/postinst
debian/DEBIAN/prerm
debian/lib/systemd/system/cke-localproxy.service
ignitions/common/files/etc/resolv.conf
pkg/neco-worker/main.go
pkg/neco/cmd/init_local.go
worker/cke.go

and configure /etc/resolv.conf to see the local DNS service.

Run cke-localproxy

---

.gitignore
Makefile
Makefile.common
Makefile.tools

Add logcli to operation packages

---

dctest/Makefile
dctest/test.sh
menu/assets/squid.conf
menu/testdata/squid.conf

`go mod download` changes go.sum in a different way from `go mod tidy`.
It's annoying.

Don't run go mod download

---

README.md
bin/watch_boot0
bin/watch_podlogs
bin/watch_service
go.mod
go.sum

This PR fixes watchers by using placemat v2. Also, updates the outdated document.

Fix watchers

---

dctest/join_remove_test.go
dctest/run_test.go
dctest/sabakan_state_setter_test.go
dctest/upgrade_test.go

Add helper function for exec etcdctl

---

pkg/sabakan-state-setter/controller.go

If the serf service is restarted, the connection of the serf client is closed.
In this case, `GetSerfStatus()` will never succeed unless recreating the client.
So return an error to exit sabakan-state-setter.

sabakan-state-setter: Exit if getting serf status is failed

---

image.go
progs/sabakan/upload.go

Fix image pull authentication

---

worker/cke.go
worker/sabakan.go

Fix updating contents logic

---

Makefile.common
Makefile.tools
constants.go
dctest/node-dns_test.go
debian/DEBIAN/postinst
debian/DEBIAN/prerm
debian/lib/systemd/system/cke-localproxy.service
docs/etcd.md
ignitions/common/files/etc/resolv.conf
pkg/neco-worker/main.go
pkg/neco/cmd/init_local.go
pkg/neco/cmd/teleport_config.go
progs/teleport/conf.go
progs/teleport/templates.go
storage/keys.go
storage/teleport.go
worker/cke.go

This reverts commit 6c0b6f165007234aa6ea7628b1f2c48b83f15cc3.

Reinstall cke-localproxy

---

artifacts.go
dctest/cke_test.go
dctest/suites_test.go
debian/lib/systemd/system/backup-cke-etcd.service
debian/lib/systemd/system/node-exporter.service
debian/usr/sbin/backup-cke-etcd

expose result of backup-cke-etcd unit via node_exporter

---

docs/ignition.md
ignitions/common/files/etc/fstab
ignitions/common/files/opt/sbin/setup-var
ignitions/common/systemd/setup-var.service

make logical volume to persist /var/lib/systemd

---

etc/sabakan-state-setter.yml
pkg/sabakan-state-setter/config_test.go

As there is no reason to wait auto shutdown until midnight, this PR changed the scheduled shutdown time earlier

change shutdown schedule time

---

artifacts.go
constants.go
generator/generate.go
progs/promtail/conf.go
progs/promtail/conf_test.go
progs/promtail/promtail.service.tmpl
progs/promtail/promtail.yaml.tmpl
progs/promtail/service.go
worker/operator.go
worker/promtail.go

Signed-off-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>

Add promtail on boot servers

---

pkg/git-neco/cmd/draft.go
pkg/git-neco/cmd/github.go
pkg/git-neco/cmd/zenhub.go

This PR fixes the issue that `git-neco` became unable to connect an issue and PR with ZenHub API.
Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>

git-neco: Fix zenhub client to be able to connect issue and PR

---

docs/neco-worker.md
updater/release.go
updater/release_checker.go
updater/release_test.go
worker/worker.go

neco-worker: Update Neco only when the package is newer than existing

---

dctest/before_test.go
dctest/cke_test.go
dctest/coil_test.go
dctest/contents_test.go
dctest/etcdpasswd_test.go
dctest/init_test.go
dctest/join_remove_test.go
dctest/node-dns_test.go
dctest/retire_test.go
dctest/sabakan_state_setter_test.go
dctest/squid_test.go
dctest/unbound_test.go
dctest/upgrade_test.go

output stderr and stdout when error

---

artifacts.go

Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>

generate-artifacts

---

artifacts.go
dctest/upgrade_test.go
updater/release_checker.go

This PR revers neco-updater to the previous implementation.
Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>

Revert release check to allow only newer versions

---

dctest/upgrade_test.go
updater/release_checker.go

stabilize neco upgrade test

---

installer/setup/packages.go

Add ipvmadm to boot server

---

artifacts.go

generate artifacts

---

dctest/Makefile
dctest/run_test.go
dctest/upgrade_test.go
docs/dctest.md
updater/release.go
updater/release_checker.go
updater/release_test.go

Current version check is incomplete as the version check had a bug and was reverted.
This PR fix the bug.  
Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>

Fix release version check to use proper format

---

Makefile.tools

Add kustomize binary to mac and windows cli package

---

README.md
artifacts.go
docs/artifacts.md
docs/ignition.md
generator/generate.go
generator/template.go
progs/sabakan/upload.go
progs/serf/linux_test.go
types.go

rename coreos to flatcar

---

Makefile.common

Update CKE to 1.20.2

---

dctest/upgrade_test.go

Related #1560 
Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>

Remove test which should be deleted after #1560 updated

---

artifacts.go
artifacts_ignore.yaml

Revert flatcar OS image

---

etc/cke-template.yml

Add ServiceLBNodePortControl feature gate

---

artifacts.go
artifacts_ignore.yaml

Ignore etcd 3.4.16

---

Makefile.common
artifacts.go

Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>

teleport: Upgrade to v6.2.0

---

artifacts.go
dctest/ignitions_test.go
dctest/menu-ss.yml
dctest/menu.yml
docs/placemat-menu.md
menu/cluster_yaml_generator.go
menu/example/menu.yml
menu/menu.go

add property to configure disk count for PoC

---

Makefile.common

Update tool versions

---

artifacts.go
etc/coil.yaml

Update coil to 2.0.8

---

Makefile.common

Update Kustomize in sync with Argo CD container image

---

artifacts.go

update OS image

---

docs/neco.md
pkg/neco/cmd/session_log.go
pkg/neco/cmd/session_log_start.go
pkg/neco/cmd/session_log_start_test.go
progs/etcdpasswd/sshd.go
worker/etcdpasswd.go

part of https://github.com/cybozu-go/neco/issues/1411

add ssh session log recording

---

pkg/neco/cmd/reboot_and_wait.go

[reboot-and-wait] Wait for machine to become healthy

---

artifacts.go
etc/coil.yaml

Update Coil to 2.0.9

---

ignitions/common/common.yml
ignitions/common/files/etc/fstab
ignitions/common/files/etc/systemd/coredump.conf
ignitions/common/files/opt/sbin/setup-var

part of https://github.com/cybozu-go/neco/issues/1677

add dedicated LV for /var/lib/systemd/coredump

---

.circleci/config.yml
artifacts.go
artifacts_ignore.yaml
progs/etcd/templates.go

This PR updates config file to use etcd 3.4.
Also, it includes some miscellaneous update for etcd 3.4.

update config file to use etcd 3.4

---

dctest/menu-ss.yml

Scale up cs nodes

---

Makefile.common
artifacts_ignore.yaml

Update containerd to 1.5.5

---

README.md

Remove the link to deprecated neco-ubuntu repository

---

bin/run-dctest.sh

add workaround for tar failure

---

README.md

Retry to fix neco release

---

installer/Makefile
installer/patch/grub.cfg

We need a driver for Intel E810-XXV.

use HWE kernel for boot server installer

---

artifacts.go
etc/coil.yaml
installer/Makefile

Update installer to use latest deb

---

.circleci/config.yml

Disable upgrade test for release temporarily

---

.circleci/config.yml

This reverts commit 3a23e9afe14c3b9cb58131428b34c1b34adc29b0.

Revert "Disable upgrade test for release temporarily"

---

worker/deb.go

#1738 
There is no clear intention for the 10 of retry count and 10s of retry intervals.

check status code and retry the deb package download

---

worker/deb.go

neco-worker waits for installation of Neco deb to finish

---

Makefile
Makefile.tools

Remove kustomize binary for Windows and MacOS

---

Makefile
Makefile.tools

Revert "Remove kustomize binary for Windows and MacOS"

---

docs/dctest.md

Fix document: wrong SUITE

---

Makefile.common
artifacts.go

Update CKE to v1.20.5

---

artifacts.go

upgrade squid to 5.2.1

---

Makefile.common

Update moco to v0.10.6

---

Makefile.common
Makefile.tools

Update MOCO to v0.10.7

---

go.mod
go.sum
vault.go

part of https://github.com/cybozu-go/neco/issues/1774

use term package instead of gopass

---

Makefile.common

Update MOCO to 0.10.8

---

Makefile.common

Update CKE to 1.21.2

---

ignitions/common/systemd/bird.service
ignitions/common/systemd/chronyd.service

Mark bird and chronyd as realtime processes

---

Makefile.common

Update MOCO to 0.10.9

---

Makefile.common

part of https://github.com/cybozu-go/neco/issues/1772

upgrade teleport to 7.3.3

---

artifacts.go
menu/testdata/chrony-ign.yml

Update `artifacts.go`. https://github.com/cybozu/neco-containers/pull/702.

Generate artifacts.go

---

menu/cluster.go
menu/cluster_conf_generator.go
menu/cluster_test.go
menu/testdata/chrony-ign.yml
pkg/placemat-menu/main.go

Fix menu test

---

ignitions/common/networkd/01-eth0.network
ignitions/common/networkd/01-eth1.network
ignitions/roles/boot/site.yml

Add ignition for boot

---

pkg/neco/cmd/session_log_start.go

part of https://github.com/cybozu-go/neco/issues/1867

fix a crash when the current user is unknown.

---

artifacts.go
etc/coil.yaml

Update coil to 2.0.14

---

Makefile.common

Update ArgoCD to v2.1.8

---

pkg/neco/cmd/tpm_clear.go

Add supported machine types for `tpm clear`

---

debian/lib/systemd/system/teleport-node.service

Allow boot-admin team to access teleport pod

---

Makefile.common

upgrade teleport to 8.0.6

---

docs/neco.md
pkg/neco/cmd/config_get.go
pkg/neco/cmd/config_set.go
storage/config.go
storage/keys.go

Remove "neco config set/get dns"

---

Makefile.common

Update Argo CD to v2.2.2

---

artifacts.go

Update setup-hw version to v1.10.0

---

etc/sabakan-state-setter.yml

Add machine-type for sabakan-state-setter

---

Makefile.common

part of https://github.com/cybozu-go/neco/issues/1859

use CKE 1.22.1

---

ignitions/common/common.yml
ignitions/common/files/opt/sbin/disable-nic-offload
ignitions/common/files/opt/sbin/neco-wait-dhcp-online
ignitions/common/systemd/disable-nic-offload.service

Fix ignition to work on machines with new nic names

---

etc/sabakan-state-setter.yml

Fix sabakan-state-setter for R7525

---

ignitions/common/files/opt/sbin/setup-local-network

Add new NICs for post-boot script

---

installer/Makefile

Update the base Ubuntu image to 20.04.3

---

Makefile.common

Update Argo CD to v2.2.5

---

.circleci/config.yml
Makefile
Makefile.tools
artifacts.go
bin/curl-github
bin/run-dctest.sh
bin/wget-github
dctest/Makefile

Send token when downloading materials from GitHub

---

dctest/boot-seed.yml.template

- add alias for `kubectl`
- run `ckecli kubernetes issue`

Improve bashrc

---

debian/lib/systemd/system/neco-updater.service
debian/lib/systemd/system/neco-worker.service

neco-updater.service and neco-updater.service sometimes fail.

Increase the retry interval of neco-updater.service and neco-worker.service.

---

artifacts.go
ignitions/common/common.yml
ignitions/common/files/etc/k8s-containerd/conf.d/docker.elastic.co/hosts.toml
ignitions/common/files/etc/k8s-containerd/conf.d/docker.io/hosts.toml
ignitions/common/files/etc/k8s-containerd/conf.d/ghcr.io/hosts.toml
ignitions/common/files/etc/k8s-containerd/conf.d/quay.io/hosts.toml
ignitions/common/files/etc/k8s-containerd/docker.io/hosts.toml

Add registry mirror settings

---

dctest/setup_test.go
debian/lib/systemd/system/neco-updater.service
debian/lib/systemd/system/neco-worker.service

- Shorten the services retry interval
- Wait for the services to stabilize in setup_test

Stabilize neco-worker.service and neco-updater.service

---

debian/etc/systemd/system.conf.d/50-cybozu.conf
ignitions/common/files/etc/systemd/system.conf.d/50-cybozu.conf

Add settings for the boot server file opening limits.

---

artifacts.go
pkg/neco/cmd/reboot_worker.go

Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>

add options for sabactl machines get

---

artifacts.go

Update Flatcar Container Linux to 3033.2.3

---

Makefile
dctest/Makefile
installer/Makefile

Show curl's error messages in Makefiles

---

Makefile.common

part of https://github.com/cybozu-go/neco/issues/1947

update teleport to 8.3.4

---

bin/env

Parameterize ZONE of dctest

---

artifacts.go

Update sabakan to 2.11.0

---

artifacts.go

Regular Update (2022-03)

---

ignitions/common/files/opt/sbin/setup-var

Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
issue: https://github.com/cybozu/csa/issues/76

expand containerd size.

---

Makefile.common

Update CKE to 1.22.2

---

artifacts.go
installer/customize-cloud-image

Fix #1969
Update `artifacts.go`

Fix customize-cloud-image script

---

Makefile.common

Update CKE to 1.22.3

---

etc/coil.yaml
etc/squid.yml
etc/unbound.yml

Add node.cybozu.io/cluster-not-ready to squid, unbound and coil-contoller

---

ignitions/common/files/opt/sbin/setup-local-network

part of https://github.com/cybozu-go/neco/issues/1978

wait for network interfaces to have expected addresses

---

artifacts.go

update etcd to 3.5.4

---

Makefile.common

update cke to 1.22.4

---

artifacts.go
dctest/upgrade_test.go

Remove temporary code from upgrade test

---

debian/DEBIAN/postinst
debian/DEBIAN/prerm
debian/lib/systemd/system/export-unit-status.service
debian/lib/systemd/system/export-unit-status.timer
debian/usr/sbin/export-unit-status

Export statuses of several systemd services on boot servers

---

artifacts.go

Update artifacts for Flatcar 3139.2.1

---

Makefile
Makefile.tools

part of https://github.com/cybozu-go/neco/issues/1956

add yq to operation tools

---

artifacts.go
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Tested the production version upgrade(cilium.yaml) manually.

Update Cilium to 1.11.5

---

Makefile.tools

part of https://github.com/cybozu-go/neco/issues/1956

fix permission of yq binary

---

etc/cke-template-pre.yml
etc/cke-template.yml

Run kubelet image GC earlier than hard eviction

---

Makefile.common
dctest/squid_test.go
dctest/unbound_test.go
dctest/upgrade_test.go
etc/squid.yml
etc/unbound.yml
ignitions/common/common.yml
ignitions/common/systemd/cke-image-unbound_exporter.service

part of https://github.com/cybozu-go/neco/issues/1975

add unbound_exporter to internet-egress unbound/squid

---

dctest/contents_test.go

Fix update of etcd parameters for dctest

---

artifacts.go

Update Flatcar Container Linux to 3139.2.2

---

artifacts.go
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Update cilium to 1.11.6

---

artifacts.go

Update Vault to 1.11.0.1

---

artifacts.go

Update Flatcar Container Linux to 3139.2.3

---

debian/usr/sbin/setup-setup-hw
ignitions/common/common.yml
ignitions/common/files/opt/sbin/setup-setup-hw
ignitions/common/systemd/setup-hw.service
progs/setuphw/templates.go

Disable periodic iDRAC reset for Dell 15G servers

---

dctest/before_test.go

Extend eventually timeout

---

Makefile.common

Update CKE to 1.22.7, Kubernetes to 1.22.12

---

cilium/pre/bgp_config.yaml
cilium/pre/kustomization.yaml
cilium/pre/upstream.yaml
cilium/pre/values.yaml
dctest/l4lb_test.go
dctest/suites_test.go
dctest/testdata/l4lb.yaml
dctest/testdata/l4lb_client.yaml
etc/cilium-pre.yaml
etc/cke-template-pre.yml

This reverts commit f21c91be2ddc29626b5ca50da8146f474948d076.

Enable Cilium L4LB

---

artifacts.go
artifacts_ignore.yaml

Upgrade Flatcar to 3227.2.1

---

.github/ISSUE_TEMPLATE/epic.md

issue-template: clarify what "three people" consist of.

---

.circleci/config.yml
Makefile.common
docs/neco.md
etc/cke-template.yml
pkg/neco/cmd/reboot_and_wait.go
pkg/neco/cmd/reboot_check.go
pkg/neco/cmd/reboot_worker.go

part of https://github.com/cybozu-go/neco/issues/2010

parallel reboot feature

---

docs/neco.md
etc/cke-template.yml
pkg/neco/cmd/power.go

add option to wait for stop to `neco power` subcommand.

---

ignition-template/settings.json
ignitions/common/common-gcp0.yml
ignitions/common/common-stage0.yml
ignitions/common/files/etc/k8s-containerd/conf.d/ghcr.io/hosts.toml

Added setting to enable mirror registry for ghcr.io.
Signed-off-by: Taichi Takemura [taichi-takemura@cybozu.co.jp](mailto:taichi-takemura@cybozu.co.jp)

Add ghcr.io mirror settings

---

artifacts.go

update flatcar version to 3227.2.2

---

etc/cke-template.yml

Record audit logs related to ECK

---

ignition-template/settings.json
ignitions/common/common-gcp0.yml
ignitions/common/common-stage0.yml
ignitions/common/files/etc/k8s-containerd/conf.d/docker.elastic.co/hosts.toml

Revert enable registry mirror

---

ignition-template/settings.json
ignitions/common/common-gcp0.yml
ignitions/common/common-stage0.yml
ignitions/common/files/etc/k8s-containerd/conf.d/docker.elastic.co/hosts.toml

Enable elastic registry mirror

---

Makefile.common

use cke 1.23.1

---

artifacts.go
etc/coil.yaml

Upgrade coil to 2.1.2

---

pkg/generate-sabakan-machines/cmd/root.go

Fix parsing rack number

---

README.md
dctest/Makefile
docs/ignition.md
generator/generate.go

part of https://github.com/cybozu-go/neco/issues/2082.

Rename flatcar-linux to flatcar

---

etc/cke-template.yml

Revert "Record audit logs related to ECK"

---

Makefile.common
etc/unbound.yml
ignitions/common/files/etc/sysctl.d/70-cybozu.conf

I changed `etc/unbound.yml` and `ignitions/common/files/etc/sysctl.d/70-cybozu.conf`.
This PR changes unbound configurations and sysctl parameters to tune unbound.

change parameters for unbound tuning

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
etc/cilium-pre.yaml

Enable Cilium XDP acceleration

---

go.mod
ignition-template/Makefile
ignition-template/main.go

Added a function to generate a file using ignition template.
You can check the operation with the following command.
```
make build
./bin/configgenerator --cluster=<cluster name> <role>
```

Add function to show differences in files generated from ignition-template

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/values.yaml
etc/cilium-pre.yaml

Revert "Enable Cilium XDP acceleration"

---

artifacts.go

update bird and chrony

---

artifacts.go

Update serf to 0.10.0

---

docs/ignition-template.md
ignition-template/main.go

Change output destination to stdout

---

cilium/pre/bgp_config.yaml
cilium/prod/bgp_config.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Advertise routes for Loadbalancer service from cs nodes

---

artifacts.go
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Update cilium image to 1.11.6.3

---

installer/setup/main.go

Use faster Ubuntu mirror to setup boot servers

---

artifacts.go

update squid 5.7.0

---

Makefile.common

Update CKE to 1.23.4

---

etc/cke-template.yml

Tolerate Cilium taint for control plane nodes

---

Makefile.common

Update Teleport to 9.3.22

---

artifacts.go

Update Flatcar to 3227.2.4

---

.circleci/config.yml
Makefile.common
go.mod
go.sum

Update etcd to v3.5.5

---

installer/setup/packages.go

Add mechanism to update snapd

---

artifacts.go
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

This PR updates cilium, cilium-operator and hubble-relay image to 1.11.11. Also it upgrades the flatcar.

Update Cilium to 1.11.11

---

dctest/menu-ss.yml

Co-authored-by: ESASHIKA Kaoru <kaoru-esashika@cybozu.co.jp>

expand cs storage size to expand ceph osd size

---

Makefile.tools

Fix tools extraction not to contaminate shared directory

---

artifacts_ignore.yaml

Ignore etcd v3.5.6 while under evaluation

---

artifacts_ignore.yaml
dctest/before_test.go
installer/setup/main.go

Hold cloud-init to prevent boot setup failure

---

progs/vault/templates.go

part of https://github.com/cybozu-go/neco/issues/2162

extend prometheus_retention_time for Vault

---

artifacts.go

Update Flatcar 3374.2.1

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

This PR removes three labels from Cilium's identity-relevant labels.

Opt-out some labels from Cilium's identity-relevant labels

---

ext/http.go
installer/setup/main.go

Add comment

---

updater/github.go

also, do not use `sort.Sort` to find latest release.
This PR must be released before https://github.com/cybozu-go/neco/pull/2174 is merged.

check tag prefix while listing GitHub releases

---

Makefile.common

Update CKE to 1.23.7

---

artifacts.go

Update setup-hw to 1.13.0

---

cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium.yaml

Enable IPIP DSR dispatch mode in prod

---

artifacts.go
etc/coil.yaml
ignition-template/settings.json
ignitions/roles/cs/site-stage0.yml
ignitions/roles/cs/site-stage1.yml
ignitions/roles/cs/site.yml
ignitions/roles/cs/systemd/cpu-governor.service
ignitions_test.go

This PR should include the following change:
https://github.com/cybozu-go/setup-hw/pull/82

Set only cs cpu governor to performance

---

artifacts.go
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Update cilium operator

---

Makefile.common

- Update CKE 1.24.1
- Update K8S_VERSION 1.24.9 in Makefile.common used by downloading kubectl

Update kubernetes 1.24.9, cke 1.24.1

---

docs/ignition-template.md
docs/procedure.md

Signed-off-by: Toru Komatsu <k0ma@utam0k.jp>
Aligned with other docs.

docs: Just a small correction

---

Makefile.common

Update CKE to 1.24.2

---

bin/run-dctest.sh
dctest/testdata/l4lb_client.yaml

ci: Use Ubuntu 22.04 Cloud Image if available

---

installer/setup/packages.go

Purge ubuntu-release-upgrader-core package 

---

.circleci/config.yml

ci: Relax CI workflow to allow release w/o upgrade test

---

.circleci/config.yml
artifacts.go
artifacts_ignore.yaml

This reverts commit 2cdb0793b77bebb43741522c076bd8b9b06b086b.

Revert temporary changes of release workflow

---

artifacts.go

Update Vault to 1.11.6

---

artifacts.go

Upgrade Flatcar to 3374.2.4

---

artifacts.go
etc/coil.yaml

Update coil to v2.3.0

---

artifacts.go

Update vault in artifacts to 1.13.0.1

---

artifacts.go

Update promtail v2.7.3

---

artifacts.go
ignition-template/settings.json

Fix cpu governor setting for stage0

---

artifacts.go

promtail v2.7.4

---

debian/usr/sbin/setup-setup-hw
ignition-template/settings.json
ignitions/common/common.yml
ignitions/common/files/opt/sbin/setup-setup-hw
ignitions/common/systemd/setup-hw.service
progs/setuphw/templates.go

This PR reverts https://github.com/cybozu-go/neco/pull/2023 .
It is not appropriate to simply run "git revert" because we have introduced the mechanism of "ignition-template."

Resume daily iDRAC reset

---

debian/lib/systemd/system/node-exporter.service
ignitions/common/systemd/node-exporter.service

Disable ipvs metrics

---

Makefile.common

Update teleport 11.3.10

---

artifacts.go

Upgrade flatcar to 3510.2.0

---

etc/cke-template.yml

Disable parallel reboot to prevent Ceph degradation

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
etc/cilium-pre.yaml

Enable cilium_bpf_map_pressure metrics in stage

---

artifacts.go

Update Flatcar stable to 3510.2.1

---

Makefile.common

Update kubeseal to 0.19.5

---

Makefile
Makefile.tools
installer/Makefile

Disable CGO to build statically linked binaries

---

Makefile.common

Update monitoring tools

---

artifacts.go
artifacts_ignore.yaml

Upgrading squid and cilium separately because we can't upgrade them at the same time

Upgrade squid to 5.8.0.2

---

.circleci/config.yml
dctest/etcdpasswd_test.go

Add logs to discover the cause of ssh hand shake error in etcdpasswd

---

artifacts.go
artifacts_ignore.yaml
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Upgrade Cilium to 1.12.10

---

artifacts.go
artifacts_ignore.yaml
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

This reverts commit e4ba69d008fe746af679f20be9a0be8ae83653d2.

Revert "Upgrade Cilium to 1.12.10"

---

Makefile.common
cilium/pre/kustomization.yaml
cilium/prod/kustomization.yaml
coil/daemonset.yaml
coil/kustomization.yaml
dctest/coil_test.go
etc/cilium-pre.yaml
etc/cilium.yaml
etc/coil.yaml

Update CKE to 1.25.6

---

Makefile.common

Update CKE to 1.25.7

---

Makefile.common

Update CKE to 1.25.8

---

artifacts.go
etc/coil.yaml

Update coil to v2.4.0

---

Makefile.common

This PR updates teleport(tsh) to v12.4.10.

Update teleport to v12.4.10

---

artifacts.go

Update flatcar stable to 3510.2.5

---

Makefile.common

Update CKE to 1.25.9

---

artifacts.go
artifacts_ignore.yaml
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Update cilium to 1.12.11

---

storage/worker_watcher.go

Fix to check error of etcd watch response

---

Makefile.common

Update Teleport to 13.3.1

---

ignitions/common/files/etc/k8s-containerd/config.toml

Activate containerd metrics port

---

dctest/Makefile

Fix reference to GOPATH

---

etc/cke-template.yml

Activate PodSchedulingReadiness feature gate

---

etc/cke-template.yml

add command_interval

---

artifacts.go

3510.2.6 → 3510.2.7
https://www.flatcar.org/releases#release-3510.2.7

update flatcar version to 3510.2.7

---

Makefile.common

update Argocd to 2.8.3

---

artifacts.go

update vault to 1.14.3

---

Makefile
Makefile.tools

Add jsonnet-lint to neco-operation-cli

---

Makefile.common
artifacts.go

Update Teleport to 13.4.0

---

Makefile.common

MOCO v0.17.0

---

artifacts.go
artifacts_ignore.yaml
dctest/join_remove_test.go

Reset systemd-networkd-wait-online on boot-3

---

dctest/init_test.go

Wait sabakan-state-setter.service in bootstrap

---

Makefile.tools

don't use wget itself directly in Makefile.tools

---

artifacts_ignore.yaml

Ignore squid 6.4

---

Makefile
Makefile.common
Makefile.tools

- Add flame graph script for necoperf

Add flame graph script to operation-cli-linux

---

artifacts.go

This PR updates artifacts.go because new etcd container image has been generated.
ref: https://github.com/cybozu/neco-containers/pull/1136

etcd 3.5.10

---

artifacts.go

Update setup-hw to 1.15.0

---

Makefile.common

Update MOCO to v0.18.1

---

cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium.yaml

Signed-off-by: naoki-take <naoki-take@cybozu.co.jp>

Enables cilium_bpf_map_pressure to prod

---

artifacts_ignore.yaml

Ignore new cilium related images

---

Makefile.common

Update ArgoCD to 2.8.6

---

artifacts.go
artifacts_ignore.yaml
cilium/pre/upstream.yaml
cilium/prod/upstream.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

This reverts commit 4052bdc40fd0c82336d7844e6a4d7b9200ea353d.

Revert "Ignore new cilium related images"

---

artifacts.go
artifacts_ignore.yaml
etc/coil.yaml

This reverts commit 0ae32d9296070c3f7931abebeac7e5ff63d06e8f.

Revert "Update artifacts.go"

---

Makefile.common
go.mod
go.sum

I was adding the flmegraph and necoperf variables in the wrong place.
I will correct this while upgrading the CKE version.

Update CKE to 1.26.3

---

artifacts_ignore.yaml

add sabakan v3.0.0 to artifact_ignore

---

Makefile.common

part of https://github.com/cybozu-private/neco-tasks/issues/39

teleport 13.4.7

---

artifacts.go
artifacts_ignore.yaml

Ignore coil 2.5.1

---

Makefile.common

part of https://github.com/cybozu-private/neco-tasks/issues/23

nerdctl v1.7.0

---

artifacts.go
etc/cke-template.yml

Record resource changes initiated by SAs of teleport namespace

---

ignitions/common/systemd/serf.service
progs/serf/templates.go

Set memory limit for serf to mitigate memory leak

---

bin/watch_podlogs
bin/watch_podlogs_directly

add stern options to gather all pod container logs

---

Makefile.common
dctest/unbound_test.go
dctest/upgrade_test.go
etc/squid.yml
etc/unbound.yml
go.mod
go.sum

Enable DNSSEC validation

---

dctest/menu-ss.yml

increase disk size of cs nodes for neco-apps CI

---

artifacts.go

Flatcar OS 3602.2.3

---

artifacts.go

Update etcdpasswd to v1.4.5

---

dctest/menu-ss.yml
dctest/menu.yml
docs/placemat-menu.md
menu/assets/bird_spine.conf
menu/cluster.go
menu/cluster_conf_generator.go
menu/example/menu.yml
menu/menu.go
menu/testdata/bird_spine1.conf
menu/testdata/bird_spine2.conf

- Rename the `Ingress` network to `Egress`
- Update the Egess network prefix from `/26` to `/25`

Update egress network prefix

---

Makefile.tools
bin/neco-download-dir-cache.sh

cache download directory using neco-ci-blob-cache

---

pkg/neco/cmd/bmc_repair_dell_discharge.go

neco CLI: Use "powercycle" instead of "hardreset" for Dell discharging

---

artifacts.go

update squid to 6.6

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Switch to Geneve from IPIPCNI

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

This reverts commit a4d724aaa3c57a7da88cf2a1e2fc43e3fd5e6549.

Revert "Switch to Geneve from IPIPCNI (#2473)"

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Switch DSR move from IPIPCNI to Geneve

---

artifacts_ignore.yaml

Ignore newer coil

---

debian/usr/sbin/check-machine-state
etc/cke-template.yml

Fix CKE config for reparing

---

ext/http.go
installer/setup/main.go

Remove deprecated DualStack flag

---

Makefile
Makefile.common
Makefile.tools

Add commend line tool for cert-manager

---

ignitions/common/systemd/node-exporter.service

This reverts commit e4fc21c47b01e6b95c9d63e92dff405927fe5b82.

Revert "Enable node_exporter network_route collector"

---

bin/clusterdump
bin/necoip
bin/nsdump
dctest/suites_test.go
dctest/tools_test.go

`clusterdump` did not work properly, so I fixed it and added tests.

Fix clusterdump and verify it

---

Makefile.common

Update argocd ver 2.10 from 2.9

---

artifacts.go
artifacts_ignore.yaml

This PR update vault to 1.15.6.

Update Vault to 1.15.6

---

etc/cke-template.yml

Add topologySpreadConstraints to distribute nodes

---

Makefile.common
go.mod
go.sum

Update CKE to v1.27.9

---

etc/cke-template.yml

* specify an SSH user
* issue a power-on command once again

Fix repair queue config

---

etc/sabakan-state-setter.yml

Add new machine type

---

Makefile
Makefile.common
etc/squid-pre.yaml
etc/squid.yaml
etc/unbound-pre.yaml
etc/unbound.yaml
go.mod
go.sum
squid/base/kustomization.yaml
unbound/base/kustomization.yaml

CKE v1.27.10

---

artifacts.go

Etcd 3.5.13

---

artifacts.go

Vault 1.16.0

---

Makefile
Makefile.common
Makefile.tools

include vmalert-tool in neco-operation-cli

---

Makefile.common

Update cmctl to 1.14.4

---

Makefile.common
go.mod
go.sum

Update CKE to 1.27.11 to use auto-repair

---

dctest/squid_test.go
etc/squid-pre.yaml
squid/pre/deployment.yaml

Increase squid resources for load test

---

artifacts.go
artifacts_ignore.yaml
etc/coil-pre.yaml
etc/coil.yaml

This reverts commit 5c25d4f121a62e264628be01ee8e8e7cd0ca97e8.

Revert "Update coil to 2.6.1"

---

Makefile.common
artifacts_ignore.yaml
go.mod
go.sum

Update CKE 1.28.3

---

etc/cke-template.yml

Audit creation of cilium.io resources

---

cilium/pre/kustomization.yaml
cilium/prod/kustomization.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Update maxUnavailable for cilium-agent

---

artifacts.go

Update setup-hw to v1.17.0

---

Makefile.common
go.mod
go.sum

Update CKE to 1.28.5

---

artifacts.go

Signed-off-by: Maho Takara <takara@cybozu.co.jp>

Update flatcar to 3815.2.4

---

etc/cke-template.yml

fix 
- https://github.com/cybozu-go/neco/pull/2593

update audit log policy

---

pkg/neco/cmd/rebooter.go
pkg/neco/cmd/rebooter_add.go
pkg/neco/cmd/rebooter_reboot_woker.go

- fix the problem that if kubeconfig is expired, renew of kubeconfig will be failed

minor fix of neco-rebooter

---

Makefile.common

ref. https://github.com/cybozu-private/neco-apps/pull/5111

Bump Argo CD version to 2.11.4

---

artifacts.go

generate-artifacts: promtail 2.9.9.1

---

artifacts.go

generate-artifacts: setup-hw 1.17.0

---

docs/procedure.md

Signed-off-by: Tomoki Sugiura <tomoki-sugiura@cybozu.co.jp>

Remove git-neco

---

Makefile.common

Revert "Bump Argo CD version to 2.11.4"

---

pkg/neco-rebooter/controller.go
pkg/neco-rebooter/utils.go
pkg/neco-rebooter/utils_test.go

Fixed a bug that groups did not move in order.

fix behavior of moveToNextGroup

---

.circleci/config.yml
artifacts_ignore.yaml
bin/watch_console

Watch all nodes' console

---

dctest/etcdpasswd_test.go
dctest/machines_test.go

This PR fixes recent flaky tests.
The commands retried are confirmed to be idempotent.

Fix flaky tests

---

dctest/bmc-user.json

Add the support user for virtual BMC on dctest

Add user for bmc on dctest

---

debian/DEBIAN/prerm
debian/lib/systemd/system/trigger-reboot-all-nodes.service
debian/lib/systemd/system/trigger-reboot-all-nodes.timer
debian/usr/bin/trigger-reboot-all-nodes

Add systemd service and timer for triggering daily reboot all nodes on dev environment.

Add feautre to perform daily reboot all nodes in dev environment

---

go.mod
go.sum

Apply following security fix
- https://github.com/cybozu-go/neco/security/dependabot
- https://github.com/cybozu-go/neco/security/dependabot/11
- https://github.com/cybozu-go/neco/security/dependabot/19

Securiy fix cloudflare/circ

---

dctest/sabakan_test.go

dctest: Retry sabactl on initialization

---

artifacts.go
artifacts_ignore.yaml
ignitions/common/files/etc/fstab

Revert "Flatcar OS 3975.2.1"

---

ignitions/common/files/etc/fstab

Add dependencies to fstab

---

ignitions/common/files/opt/sbin/setup-local-network

Show Network I/F during network initialization

---

artifacts.go
artifacts_ignore.yaml

Update Flatcar OS to 3975.2.2

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
etc/cilium-pre.yaml

Update Cilium conntrack-gc-max-interval to 30m only for stage

---

cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium.yaml

Update Cilium conntrack-gc-max-interval to 30m for prod

---

artifacts.go

Update serf to 0.10.1.7

---

artifacts.go

Update etcdpasswd to v1.4.9

---

artifacts.go

See-also: https://github.com/cybozu-private/neco-tasks/issues/317

Update Sabakan to 3.1.4, Promtail to 3.2.1.2

---

etc/cke-template.yml

Remove ss2 setting from cke-template

---

artifacts_ignore.yaml

Suppress undesirable effect from:
- https://github.com/cybozu/neco-containers/pull/1482

Ignore Squid 6.12.0.2

---

artifacts_ignore.yaml

Ignore Cilium 1.15.11.1-rc.1

---

artifacts_ignore.yaml

Ignore Cilium operator of 1.15

---

cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium-pre.yaml
etc/cilium.yaml

Shorten CT TCP Timeout

---

Makefile.common
go.mod
go.sum

Update CKE to v1.29.2

---

Makefile.common
go.mod
go.sum

Revert "Update CKE to v1.29.2"

---

ignitions/roles/ss2/files/etc/udev/crypt-base-path

- **fix crept-base-path to find BOSS correctly**

fix crypt base path ss2 (again)

---

artifacts_ignore.yaml

Ignore Cilium 1.15.12.1-rc.1

---

artifacts_ignore.yaml

Ignore hubble-relay 1.15.12.1

---

pkg/neco/cmd/root.go

Fix help message

---

dctest/before_test.go
dctest/reboot_test.go
dctest/run_test.go
docs/installer.md
installer/setup/network.go
installer/setup/templates.go

This PR add `boot` network interface to boot servers.

Add boot network interface

---

artifacts.go
etc/coil-pre.yaml
etc/coil.yaml

Update coil v2.8.0

---

Makefile
dctest/cilium_test.go
dctest/run_test.go

This PR rewrites some tests for Cilium.

test: refactor cilium-related checks

---

dctest/cke_test.go
dctest/contents_test.go
dctest/ignitions_test.go
dctest/reboot_test.go
dctest/retire_test.go
dctest/run_test.go
dctest/sabakan_state_setter_test.go
dctest/upgrade_test.go

dctest: refine helper function for getting sabakan machines

---

artifacts_ignore.yaml

Ignore Cilium 1.15.13

---

debian/lib/systemd/system/boot-ip-setter.service
debian/lib/systemd/system/neco-rebooter.service

fix systemd services to restart infinitely.
upgrade-test definitely fails now, so I'll edit branch protection rule and merge this PR after I get approve.

fix systemd services

---

Makefile.common
etc/cke-template.yml
etc/squid-pre.yaml
etc/squid.yaml
etc/unbound-pre.yaml
etc/unbound.yaml
squid/base/kustomization.yaml
unbound/base/kustomization.yaml

This PR reverts following PR and update CKE to 1.30.5
- https://github.com/cybozu-go/neco/pull/2777

Update CKE to 1.30

---

docs/neco-updater.md
go.mod
go.sum
pkg/neco/cmd/config_get.go
pkg/neco/cmd/config_set.go
storage/config.go
storage/keys.go
updater/release_checker.go

I'll not merge this PR until k8s 1.30 is applied.

implement automatic night release feature

---

artifacts.go
artifacts_ignore.yaml

Ignore Cilium 1.15.13.2

---

etc/squid-pre.yaml
etc/squid.yaml
squid/base/deployment.yaml

squid: add new security-relevant label

---

cilium/dctest/upstream.yaml
cilium/dctest/values.yaml
cilium/pre/upstream.yaml
cilium/pre/values.yaml
cilium/prod/upstream.yaml
cilium/prod/values.yaml
etc/cilium-dctest.yaml
etc/cilium-pre.yaml
etc/cilium.yaml
etc/unbound-pre.yaml
etc/unbound.yaml
unbound/base/deployment.yaml

hubble, unbound: add new security-relevant label

---

dctest/l4lb_test.go

test: refactor testL4LB
